#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BinkMediaPlayer

#include "Basic.hpp"


namespace SDK
{

// Enum BinkMediaPlayer.EBinkMediaPlayerBinkDrawStyle
// NumValues: 0x0007
enum class EBinkMediaPlayerBinkDrawStyle : uint8
{
	BMASM_Bink_DS_RenderToTexture            = 0,
	BMASM_Bink_DS_OverlayFillScreenWithAspectRatio = 1,
	BMASM_Bink_DS_OverlayOriginalMovieSize   = 2,
	BMASM_Bink_DS_OverlayFillScreen          = 3,
	BMASM_Bink_DS_OverlaySpecificDestinationRectangle = 4,
	BMASM_Bink_DS_OverlayFillScreenExpandToPreserveAspectRatio = 5,
	BMASM_Bink_DS_MAX                        = 6,
};

// Enum BinkMediaPlayer.EBinkMediaPlayerBinkSoundTrack
// NumValues: 0x000A
enum class EBinkMediaPlayerBinkSoundTrack : uint8
{
	BMASM_Bink_Sound_None                    = 0,
	BMASM_Bink_Sound_Simple                  = 1,
	BMASM_Bink_Sound_LanguageOverride        = 2,
	BMASM_Bink_Sound_51                      = 3,
	BMASM_Bink_Sound_51LanguageOverride      = 4,
	BMASM_Bink_Sound_51Custom                = 5,
	BMASM_Bink_Sound_71                      = 6,
	BMASM_Bink_Sound_71LanguageOverride      = 7,
	BMASM_Bink_Sound_71Custom                = 8,
	BMASM_Bink_Sound_MAX                     = 9,
};

// Enum BinkMediaPlayer.EBinkMediaPlayerBinkBufferModes
// NumValues: 0x0004
enum class EBinkMediaPlayerBinkBufferModes : uint8
{
	BMASM_Bink_Stream                        = 0,
	BMASM_Bink_PreloadAll                    = 1,
	BMASM_Bink_StreamUntilResident           = 2,
	BMASM_Bink_MAX                           = 3,
};

// Enum BinkMediaPlayer.EBinkMoviePlayerBinkSoundTrack
// NumValues: 0x000A
enum class EBinkMoviePlayerBinkSoundTrack : uint8
{
	MP_Bink_Sound_None                       = 0,
	MP_Bink_Sound_Simple                     = 1,
	MP_Bink_Sound_LanguageOverride           = 2,
	MP_Bink_Sound_51                         = 3,
	MP_Bink_Sound_51LanguageOverride         = 4,
	MP_Bink_Sound_51Custom                   = 5,
	MP_Bink_Sound_71                         = 6,
	MP_Bink_Sound_71LanguageOverride         = 7,
	MP_Bink_Sound_71Custom                   = 8,
	MP_Bink_Sound_MAX                        = 9,
};

// Enum BinkMediaPlayer.EBinkMoviePlayerBinkBufferModes
// NumValues: 0x0004
enum class EBinkMoviePlayerBinkBufferModes : uint8
{
	MP_Bink_Stream                           = 0,
	MP_Bink_PreloadAll                       = 1,
	MP_Bink_StreamUntilResident              = 2,
	MP_Bink_MAX                              = 3,
};

}

