#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Halo3_PersonalizationData

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Halo3_PersonalizationData.BP_Halo3_PersonalizationData_C
// 0x0000 (0x00B0 - 0x00B0)
class UBP_Halo3_PersonalizationData_C final : public UMCCCustomizationMenuData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Halo3_PersonalizationData_C">();
	}
	static class UBP_Halo3_PersonalizationData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Halo3_PersonalizationData_C>();
	}
};
static_assert(alignof(UBP_Halo3_PersonalizationData_C) == 0x000008, "Wrong alignment on UBP_Halo3_PersonalizationData_C");
static_assert(sizeof(UBP_Halo3_PersonalizationData_C) == 0x0000B0, "Wrong size on UBP_Halo3_PersonalizationData_C");

}

