#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MCCUIPopupFactory

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MCCUIPopupFactory.BP_MCCUIPopupFactory_C
// 0x0000 (0x01C0 - 0x01C0)
class UBP_MCCUIPopupFactory_C final : public UMCCUIPopupManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MCCUIPopupFactory_C">();
	}
	static class UBP_MCCUIPopupFactory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MCCUIPopupFactory_C>();
	}
};
static_assert(alignof(UBP_MCCUIPopupFactory_C) == 0x000008, "Wrong alignment on UBP_MCCUIPopupFactory_C");
static_assert(sizeof(UBP_MCCUIPopupFactory_C) == 0x0001C0, "Wrong size on UBP_MCCUIPopupFactory_C");

}

