#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MCCUINarrationManager

#include "Basic.hpp"

#include "SDCoreUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MCCUINarrationManager.BP_MCCUINarrationManager_C
// 0x0000 (0x0028 - 0x0028)
class UBP_MCCUINarrationManager_C final : public USDUINarrationManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MCCUINarrationManager_C">();
	}
	static class UBP_MCCUINarrationManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MCCUINarrationManager_C>();
	}
};
static_assert(alignof(UBP_MCCUINarrationManager_C) == 0x000008, "Wrong alignment on UBP_MCCUINarrationManager_C");
static_assert(sizeof(UBP_MCCUINarrationManager_C) == 0x000028, "Wrong size on UBP_MCCUINarrationManager_C");

}

