#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MMCGameMode

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MMCGameMode.BP_MMCGameMode_C
// 0x0008 (0x03D0 - 0x03C8)
class ABP_MMCGameMode_C final : public AMCCGameModeBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MMCGameMode_C">();
	}
	static class ABP_MMCGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MMCGameMode_C>();
	}
};
static_assert(alignof(ABP_MMCGameMode_C) == 0x000008, "Wrong alignment on ABP_MMCGameMode_C");
static_assert(sizeof(ABP_MMCGameMode_C) == 0x0003D0, "Wrong size on ABP_MMCGameMode_C");
static_assert(offsetof(ABP_MMCGameMode_C, DefaultSceneRoot) == 0x0003C8, "Member 'ABP_MMCGameMode_C::DefaultSceneRoot' has a wrong offset!");

}

