#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MCCPlayerController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MCCPlayerController.BP_MCCPlayerController_C
// 0x0008 (0x07B8 - 0x07B0)
class ABP_MCCPlayerController_C final : public AMCCPlayerController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_MCCPlayerController(int32 EntryPoint);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MCCPlayerController_C">();
	}
	static class ABP_MCCPlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MCCPlayerController_C>();
	}
};
static_assert(alignof(ABP_MCCPlayerController_C) == 0x000008, "Wrong alignment on ABP_MCCPlayerController_C");
static_assert(sizeof(ABP_MCCPlayerController_C) == 0x0007B8, "Wrong size on ABP_MCCPlayerController_C");
static_assert(offsetof(ABP_MCCPlayerController_C, UberGraphFrame) == 0x0007B0, "Member 'ABP_MCCPlayerController_C::UberGraphFrame' has a wrong offset!");

}

