#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MCCPlayerController

#include "Basic.hpp"

#include "BP_MCCPlayerController_classes.hpp"
#include "BP_MCCPlayerController_parameters.hpp"


namespace SDK
{

// Function BP_MCCPlayerController.BP_MCCPlayerController_C.ExecuteUbergraph_BP_MCCPlayerController
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MCCPlayerController_C::ExecuteUbergraph_BP_MCCPlayerController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MCCPlayerController_C", "ExecuteUbergraph_BP_MCCPlayerController");

	Params::BP_MCCPlayerController_C_ExecuteUbergraph_BP_MCCPlayerController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MCCPlayerController.BP_MCCPlayerController_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_MCCPlayerController_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MCCPlayerController_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

