#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MCCScreenFactory

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MCCScreenFactory.BP_MCCScreenFactory_C
// 0x0000 (0x0308 - 0x0308)
class UBP_MCCScreenFactory_C final : public UMCCScreenManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MCCScreenFactory_C">();
	}
	static class UBP_MCCScreenFactory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MCCScreenFactory_C>();
	}
};
static_assert(alignof(UBP_MCCScreenFactory_C) == 0x000008, "Wrong alignment on UBP_MCCScreenFactory_C");
static_assert(sizeof(UBP_MCCScreenFactory_C) == 0x000308, "Wrong size on UBP_MCCScreenFactory_C");

}

