#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ODST_CharacterCategory

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ODST_CharacterCategory.BP_ODST_CharacterCategory_C
// 0x0000 (0x0058 - 0x0058)
class UBP_ODST_CharacterCategory_C final : public UMCCCustomizationCategory
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ODST_CharacterCategory_C">();
	}
	static class UBP_ODST_CharacterCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ODST_CharacterCategory_C>();
	}
};
static_assert(alignof(UBP_ODST_CharacterCategory_C) == 0x000008, "Wrong alignment on UBP_ODST_CharacterCategory_C");
static_assert(sizeof(UBP_ODST_CharacterCategory_C) == 0x000058, "Wrong size on UBP_ODST_CharacterCategory_C");

}

