#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ODSTCustomizationSelectorDataType

#include "Basic.hpp"

#include "MCC_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ODSTCustomizationSelectorDataType.BP_ODSTCustomizationSelectorDataType_C
// 0x0000 (0x00C0 - 0x00C0)
class UBP_ODSTCustomizationSelectorDataType_C final : public UMCCCustomizationSelectorData
{
public:
	class FText GetDescription(ELockState LockState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ODSTCustomizationSelectorDataType_C">();
	}
	static class UBP_ODSTCustomizationSelectorDataType_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ODSTCustomizationSelectorDataType_C>();
	}
};
static_assert(alignof(UBP_ODSTCustomizationSelectorDataType_C) == 0x000008, "Wrong alignment on UBP_ODSTCustomizationSelectorDataType_C");
static_assert(sizeof(UBP_ODSTCustomizationSelectorDataType_C) == 0x0000C0, "Wrong size on UBP_ODSTCustomizationSelectorDataType_C");

}

