#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Reach_VoicePreviewData

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Reach_VoicePreviewData.BP_Reach_VoicePreviewData_C
// 0x0000 (0x0098 - 0x0098)
class UBP_Reach_VoicePreviewData_C final : public UMCCCustomizationVoicePreviewData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Reach_VoicePreviewData_C">();
	}
	static class UBP_Reach_VoicePreviewData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Reach_VoicePreviewData_C>();
	}
};
static_assert(alignof(UBP_Reach_VoicePreviewData_C) == 0x000008, "Wrong alignment on UBP_Reach_VoicePreviewData_C");
static_assert(sizeof(UBP_Reach_VoicePreviewData_C) == 0x000098, "Wrong size on UBP_Reach_VoicePreviewData_C");

}

