#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SceneControllerActor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SceneControllerActor.BP_SceneControllerActor_C.ExecuteUbergraph_BP_SceneControllerActor
// 0x0004 (0x0004 - 0x0000)
struct BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor) == 0x000004, "Wrong alignment on BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor");
static_assert(sizeof(BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor) == 0x000004, "Wrong size on BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor");
static_assert(offsetof(BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor, EntryPoint) == 0x000000, "Member 'BP_SceneControllerActor_C_ExecuteUbergraph_BP_SceneControllerActor::EntryPoint' has a wrong offset!");

// Function BP_SceneControllerActor.BP_SceneControllerActor_C.RegisterCamera
// 0x0010 (0x0010 - 0x0000)
struct BP_SceneControllerActor_C_RegisterCamera final
{
public:
	class FName                                   Trigger;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CameraActor;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SceneControllerActor_C_RegisterCamera) == 0x000008, "Wrong alignment on BP_SceneControllerActor_C_RegisterCamera");
static_assert(sizeof(BP_SceneControllerActor_C_RegisterCamera) == 0x000010, "Wrong size on BP_SceneControllerActor_C_RegisterCamera");
static_assert(offsetof(BP_SceneControllerActor_C_RegisterCamera, Trigger) == 0x000000, "Member 'BP_SceneControllerActor_C_RegisterCamera::Trigger' has a wrong offset!");
static_assert(offsetof(BP_SceneControllerActor_C_RegisterCamera, CameraActor) == 0x000008, "Member 'BP_SceneControllerActor_C_RegisterCamera::CameraActor' has a wrong offset!");

// Function BP_SceneControllerActor.BP_SceneControllerActor_C.OnFocalTargetChange
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) BP_SceneControllerActor_C_OnFocalTargetChange final
{
public:
	class FName                                   NewTarget;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SceneControllerActor_C_OnFocalTargetChange) == 0x000008, "Wrong alignment on BP_SceneControllerActor_C_OnFocalTargetChange");
static_assert(sizeof(BP_SceneControllerActor_C_OnFocalTargetChange) == 0x000008, "Wrong size on BP_SceneControllerActor_C_OnFocalTargetChange");
static_assert(offsetof(BP_SceneControllerActor_C_OnFocalTargetChange, NewTarget) == 0x000000, "Member 'BP_SceneControllerActor_C_OnFocalTargetChange::NewTarget' has a wrong offset!");

// Function BP_SceneControllerActor.BP_SceneControllerActor_C.SetCustomizationElement
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) BP_SceneControllerActor_C_SetCustomizationElement final
{
public:
	class FName                                   Category;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ElementID;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Preview;                                           // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SceneControllerActor_C_SetCustomizationElement) == 0x000008, "Wrong alignment on BP_SceneControllerActor_C_SetCustomizationElement");
static_assert(sizeof(BP_SceneControllerActor_C_SetCustomizationElement) == 0x000018, "Wrong size on BP_SceneControllerActor_C_SetCustomizationElement");
static_assert(offsetof(BP_SceneControllerActor_C_SetCustomizationElement, Category) == 0x000000, "Member 'BP_SceneControllerActor_C_SetCustomizationElement::Category' has a wrong offset!");
static_assert(offsetof(BP_SceneControllerActor_C_SetCustomizationElement, ElementID) == 0x000008, "Member 'BP_SceneControllerActor_C_SetCustomizationElement::ElementID' has a wrong offset!");
static_assert(offsetof(BP_SceneControllerActor_C_SetCustomizationElement, Preview) == 0x000010, "Member 'BP_SceneControllerActor_C_SetCustomizationElement::Preview' has a wrong offset!");

}

