#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SDCoreAudioInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class SDCoreAudioInterface.SDISoundActor
// 0x0000 (0x0000 - 0x0000)
class ISDISoundActor final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDISoundActor">();
	}
	static class ISDISoundActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ISDISoundActor>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(ISDISoundActor) == 0x000001, "Wrong alignment on ISDISoundActor");
static_assert(sizeof(ISDISoundActor) == 0x000001, "Wrong size on ISDISoundActor");

// Class SDCoreAudioInterface.SDISoundSource
// 0x0000 (0x0000 - 0x0000)
class ISDISoundSource final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDISoundSource">();
	}
	static class ISDISoundSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<ISDISoundSource>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(ISDISoundSource) == 0x000001, "Wrong alignment on ISDISoundSource");
static_assert(sizeof(ISDISoundSource) == 0x000001, "Wrong size on ISDISoundSource");

// Class SDCoreAudioInterface.SDISoundSourceOwner
// 0x0000 (0x0000 - 0x0000)
class ISDISoundSourceOwner final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDISoundSourceOwner">();
	}
	static class ISDISoundSourceOwner* GetDefaultObj()
	{
		return GetDefaultObjImpl<ISDISoundSourceOwner>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(ISDISoundSourceOwner) == 0x000001, "Wrong alignment on ISDISoundSourceOwner");
static_assert(sizeof(ISDISoundSourceOwner) == 0x000001, "Wrong size on ISDISoundSourceOwner");

}

