#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SDCoreAudio

#include "Basic.hpp"

#include "SDCoreAudioInterface_structs.hpp"
#include "SDCoreAudio_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class SDCoreAudio.SDAnimNotify_PlaySound
// 0x0030 (0x0068 - 0x0038)
class USDAnimNotify_PlaySound final : public UAnimNotify
{
public:
	class FString                                 AttachSocket;                                      // 0x0038(0x0010)(Edit, BlueprintReadOnly, ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FSDSoundSourceConfig                   SoundSourceConfig;                                 // 0x0048(0x0020)(Edit, BlueprintReadOnly, NoDestructor, Protected, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDAnimNotify_PlaySound">();
	}
	static class USDAnimNotify_PlaySound* GetDefaultObj()
	{
		return GetDefaultObjImpl<USDAnimNotify_PlaySound>();
	}
};
static_assert(alignof(USDAnimNotify_PlaySound) == 0x000008, "Wrong alignment on USDAnimNotify_PlaySound");
static_assert(sizeof(USDAnimNotify_PlaySound) == 0x000068, "Wrong size on USDAnimNotify_PlaySound");
static_assert(offsetof(USDAnimNotify_PlaySound, AttachSocket) == 0x000038, "Member 'USDAnimNotify_PlaySound::AttachSocket' has a wrong offset!");
static_assert(offsetof(USDAnimNotify_PlaySound, SoundSourceConfig) == 0x000048, "Member 'USDAnimNotify_PlaySound::SoundSourceConfig' has a wrong offset!");

// Class SDCoreAudio.SDSoundActor
// 0x0018 (0x0340 - 0x0328)
class ASDSoundActor final : public AActor
{
public:
	uint8                                         Pad_328[0x8];                                      // 0x0328(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class USDSoundSource*                         SoundSource;                                       // 0x0330(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FSDSoundActorConfig                    Config;                                            // 0x0338(0x0002)(Edit, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_33A[0x6];                                      // 0x033A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnSoundEventFinished(int32 PlayingId);
	void Play();
	void PostEvent(const class FString& Event);
	void SetShouldDestroyAfterPlay(bool Value);
	void Stop();

	struct FVector GetLocation() const;
	bool IsPlaying() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDSoundActor">();
	}
	static class ASDSoundActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASDSoundActor>();
	}
};
static_assert(alignof(ASDSoundActor) == 0x000008, "Wrong alignment on ASDSoundActor");
static_assert(sizeof(ASDSoundActor) == 0x000340, "Wrong size on ASDSoundActor");
static_assert(offsetof(ASDSoundActor, SoundSource) == 0x000330, "Member 'ASDSoundActor::SoundSource' has a wrong offset!");
static_assert(offsetof(ASDSoundActor, Config) == 0x000338, "Member 'ASDSoundActor::Config' has a wrong offset!");

// Class SDCoreAudio.SDSoundSource
// 0x01A8 (0x03E0 - 0x0238)
class USDSoundSource final : public USceneComponent
{
public:
	uint8                                         Pad_238[0x8];                                      // 0x0238(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	UMulticastDelegateProperty_                   OnEventEnded;                                      // 0x0240(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	struct FSDSoundSourceConfig                   Config;                                            // 0x0250(0x0020)(Edit, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_270[0x20];                                     // 0x0270(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkComponent*                           AkComponent;                                       // 0x0290(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_298[0x148];                                    // 0x0298(0x0148)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	const struct FSDSoundSourceConfig GetConfig();
	float GetRTPC(const class FString& Name_0, float DefaultValue);
	struct FSDAudioEventResult PostEvent(class UAkAudioEvent* Event);
	struct FSDAudioEventResult PostEventByName(const class FString& EventName);
	struct FSDAudioEventResult PostPrimaryEvent();
	void PostTrigger(const class FString& Name_0);
	void SetConfig(const struct FSDSoundSourceConfig& NewConfig);
	void SetRTPC(const class FString& Name_0, float Value, int32 interpolationTime);
	void SetSwitch(const class FString& SwitchGroup, const class FString& SwitchState);
	void StopSounds();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDSoundSource">();
	}
	static class USDSoundSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<USDSoundSource>();
	}
};
static_assert(alignof(USDSoundSource) == 0x000008, "Wrong alignment on USDSoundSource");
static_assert(sizeof(USDSoundSource) == 0x0003E0, "Wrong size on USDSoundSource");
static_assert(offsetof(USDSoundSource, OnEventEnded) == 0x000240, "Member 'USDSoundSource::OnEventEnded' has a wrong offset!");
static_assert(offsetof(USDSoundSource, Config) == 0x000250, "Member 'USDSoundSource::Config' has a wrong offset!");
static_assert(offsetof(USDSoundSource, AkComponent) == 0x000290, "Member 'USDSoundSource::AkComponent' has a wrong offset!");

// Class SDCoreAudio.SDSoundUtils
// 0x0000 (0x0028 - 0x0028)
class USDSoundUtils final : public UBlueprintFunctionLibrary
{
public:
	static class USDSoundSource* FindSoundSource(class AActor* TargetActor, const class FString& SocketName);
	static class FString GetCurrentLanguage();
	static class USceneComponent* GetFirstDefaultListener();
	static bool IsEventResultSuccess(const struct FSDAudioEventResult& Result);
	static void LoadBankByName(const class FString& Name_0);
	static void PostEventAtLocation(const struct FSDAudioEvent& Event, const struct FVector& Location, const struct FRotator& Rotation);
	static void PostEventAtLocationByName(const class FString& EventName, const struct FVector& Location, const struct FRotator& Rotation);
	static struct FSDAudioEventResult PostEventAtSocket(const struct FSDAudioEvent& Event, class AActor* TargetActor, const class FString& SocketName);
	static struct FSDAudioEventResult PostEventAtSocketByName(const class FString& EventName, class AActor* TargetActor, const class FString& SocketName);
	static struct FSDAudioEventResult PostEventAttached(const struct FSDAudioEvent& Event, class AActor* TargetActor);
	static struct FSDAudioEventResult PostEventAttachedByName(const class FString& EventName, class AActor* TargetActor);
	static bool SetCurrentLanguage(const class FString& LanguageName);
	static void SetRTPC(const class FString& Name_0, float Value, class USDSoundSource* SoundSource, int32 interpolationTime);
	static void SetState(const class FString& StateGroup, const class FString& State);
	static class USDSoundSource* SetupSoundSource(class AActor* TargetActor, const struct FVector& Location, const struct FRotator& Rotation);
	static class USDSoundSource* SetupSoundSourceAtSocket(class AActor* TargetActor, const class FString& SocketName, const struct FVector& Location, const struct FRotator& Rotation);
	static class USDSoundSource* SetupSoundSourceAtSocketWithConfig(class AActor* TargetActor, const class FString& SocketName, const struct FVector& Location, const struct FSDSoundSourceConfig& Config, const struct FRotator& Rotation);
	static class USDSoundSource* SetupSoundSourceWithConfig(class AActor* TargetActor, const struct FVector& Location, const struct FSDSoundSourceConfig& Config, const struct FRotator& Rotation);
	static void StopAllSounds();
	static void StopPlayingId(int32 PlayingId);
	static void UnloadBankByName(const class FString& Name_0);

	int32 PostEvent(const struct FSDAudioEvent& Event);
	void PostEventByName(const class FString& EventName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDSoundUtils">();
	}
	static class USDSoundUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<USDSoundUtils>();
	}
};
static_assert(alignof(USDSoundUtils) == 0x000008, "Wrong alignment on USDSoundUtils");
static_assert(sizeof(USDSoundUtils) == 0x000028, "Wrong size on USDSoundUtils");

// Class SDCoreAudio.SDSoundVolume
// 0x0048 (0x03A8 - 0x0360)
class ASDSoundVolume final : public AVolume
{
public:
	struct FSDSoundVolumeConfig                   Config;                                            // 0x0360(0x0030)(Edit, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_390[0x18];                                     // 0x0390(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetListener(class USceneComponent* NewListener);

	struct FSDReverbState CalculateReverbStateForLocation(const struct FVector& Location) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SDSoundVolume">();
	}
	static class ASDSoundVolume* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASDSoundVolume>();
	}
};
static_assert(alignof(ASDSoundVolume) == 0x000008, "Wrong alignment on ASDSoundVolume");
static_assert(sizeof(ASDSoundVolume) == 0x0003A8, "Wrong size on ASDSoundVolume");
static_assert(offsetof(ASDSoundVolume, Config) == 0x000360, "Member 'ASDSoundVolume::Config' has a wrong offset!");

}

