#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SDEvent

#include "Basic.hpp"


namespace SDK::Params
{

// Function SDEvent.SDEventListenerComponent.ManuallyUnregister
// 0x0008 (0x0008 - 0x0000)
struct SDEventListenerComponent_ManuallyUnregister final
{
public:
	class USDEventListener*                       EventListener;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SDEventListenerComponent_ManuallyUnregister) == 0x000008, "Wrong alignment on SDEventListenerComponent_ManuallyUnregister");
static_assert(sizeof(SDEventListenerComponent_ManuallyUnregister) == 0x000008, "Wrong size on SDEventListenerComponent_ManuallyUnregister");
static_assert(offsetof(SDEventListenerComponent_ManuallyUnregister, EventListener) == 0x000000, "Member 'SDEventListenerComponent_ManuallyUnregister::EventListener' has a wrong offset!");

// Function SDEvent.SDEventListenerComponent.Register
// 0x0018 (0x0018 - 0x0000)
struct SDEventListenerComponent_Register final
{
public:
	TSubclassOf<class USDEventListener>           EventListenerClass;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class AActor*                           FilteredActor;                                     // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USDEventListener*                       ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(SDEventListenerComponent_Register) == 0x000008, "Wrong alignment on SDEventListenerComponent_Register");
static_assert(sizeof(SDEventListenerComponent_Register) == 0x000018, "Wrong size on SDEventListenerComponent_Register");
static_assert(offsetof(SDEventListenerComponent_Register, EventListenerClass) == 0x000000, "Member 'SDEventListenerComponent_Register::EventListenerClass' has a wrong offset!");
static_assert(offsetof(SDEventListenerComponent_Register, FilteredActor) == 0x000008, "Member 'SDEventListenerComponent_Register::FilteredActor' has a wrong offset!");
static_assert(offsetof(SDEventListenerComponent_Register, ReturnValue) == 0x000010, "Member 'SDEventListenerComponent_Register::ReturnValue' has a wrong offset!");

}

