#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCDialogBoxWide

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_MCCDialogBoxWide.WBP_MCCDialogBoxWide_C.ExecuteUbergraph_WBP_MCCDialogBoxWide
// 0x0038 (0x0038 - 0x0000)
struct WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue1;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue2;          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue3;          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide) == 0x000008, "Wrong alignment on WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide");
static_assert(sizeof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide) == 0x000038, "Wrong size on WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, EntryPoint) == 0x000000, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000008, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, CallFunc_GetDynamicMaterial_ReturnValue1) == 0x000018, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::CallFunc_GetDynamicMaterial_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, CallFunc_GetDynamicMaterial_ReturnValue2) == 0x000020, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::CallFunc_GetDynamicMaterial_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, K2Node_Event_IsDesignTime) == 0x000028, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide, CallFunc_GetDynamicMaterial_ReturnValue3) == 0x000030, "Member 'WBP_MCCDialogBoxWide_C_ExecuteUbergraph_WBP_MCCDialogBoxWide::CallFunc_GetDynamicMaterial_ReturnValue3' has a wrong offset!");

// Function WBP_MCCDialogBoxWide.WBP_MCCDialogBoxWide_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MCCDialogBoxWide_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_MCCDialogBoxWide_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_MCCDialogBoxWide_C_PreConstruct");
static_assert(sizeof(WBP_MCCDialogBoxWide_C_PreConstruct) == 0x000001, "Wrong size on WBP_MCCDialogBoxWide_C_PreConstruct");
static_assert(offsetof(WBP_MCCDialogBoxWide_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_MCCDialogBoxWide_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

