#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InstallerScreen

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_InstallerScreen.WBP_InstallerScreen_C.ExecuteUbergraph_WBP_InstallerScreen
// 0x0008 (0x0008 - 0x0000)
struct WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen) == 0x000004, "Wrong alignment on WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen");
static_assert(sizeof(WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen) == 0x000008, "Wrong size on WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen");
static_assert(offsetof(WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen, EntryPoint) == 0x000000, "Member 'WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_InstallerScreen_C_ExecuteUbergraph_WBP_InstallerScreen::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function WBP_InstallerScreen.WBP_InstallerScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_InstallerScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_InstallerScreen_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_InstallerScreen_C_PreConstruct");
static_assert(sizeof(WBP_InstallerScreen_C_PreConstruct) == 0x000001, "Wrong size on WBP_InstallerScreen_C_PreConstruct");
static_assert(offsetof(WBP_InstallerScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_InstallerScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

