#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsPreviewServerPingsWidget

#include "Basic.hpp"

#include "WBP_SettingsPreviewServerPingsWidget_classes.hpp"
#include "WBP_SettingsPreviewServerPingsWidget_parameters.hpp"


namespace SDK
{

// Function WBP_SettingsPreviewServerPingsWidget.WBP_SettingsPreviewServerPingsWidget_C.ExecuteUbergraph_WBP_SettingsPreviewServerPingsWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsPreviewServerPingsWidget_C::ExecuteUbergraph_WBP_SettingsPreviewServerPingsWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewServerPingsWidget_C", "ExecuteUbergraph_WBP_SettingsPreviewServerPingsWidget");

	Params::WBP_SettingsPreviewServerPingsWidget_C_ExecuteUbergraph_WBP_SettingsPreviewServerPingsWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsPreviewServerPingsWidget.WBP_SettingsPreviewServerPingsWidget_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_SettingsPreviewServerPingsWidget_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewServerPingsWidget_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsPreviewServerPingsWidget.WBP_SettingsPreviewServerPingsWidget_C.OnServerPingListChanged
// (Event, Protected, BlueprintEvent)

void UWBP_SettingsPreviewServerPingsWidget_C::OnServerPingListChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewServerPingsWidget_C", "OnServerPingListChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsPreviewServerPingsWidget.WBP_SettingsPreviewServerPingsWidget_C.PlayStaggerAnimation
// (BlueprintCallable, BlueprintEvent)

void UWBP_SettingsPreviewServerPingsWidget_C::PlayStaggerAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewServerPingsWidget_C", "PlayStaggerAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

