#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsSplitter

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_SettingsSplitter.WBP_SettingsSplitter_C.ExecuteUbergraph_WBP_SettingsSplitter
// 0x0008 (0x0008 - 0x0000)
struct WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter) == 0x000004, "Wrong alignment on WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter");
static_assert(sizeof(WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter) == 0x000008, "Wrong size on WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter");
static_assert(offsetof(WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter, EntryPoint) == 0x000000, "Member 'WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_SettingsSplitter_C_ExecuteUbergraph_WBP_SettingsSplitter::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

