#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GammaStepper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GammaStepper.WBP_GammaStepper_C
// 0x0010 (0x04C0 - 0x04B0)
class UWBP_GammaStepper_C final : public UMCCGammaStepperWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDConfigurableTextBlock*               GammaText;                                         // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_GammaStepper(int32 EntryPoint);
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_GammaStepper_C">();
	}
	static class UWBP_GammaStepper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GammaStepper_C>();
	}
};
static_assert(alignof(UWBP_GammaStepper_C) == 0x000008, "Wrong alignment on UWBP_GammaStepper_C");
static_assert(sizeof(UWBP_GammaStepper_C) == 0x0004C0, "Wrong size on UWBP_GammaStepper_C");
static_assert(offsetof(UWBP_GammaStepper_C, UberGraphFrame) == 0x0004B0, "Member 'UWBP_GammaStepper_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_GammaStepper_C, GammaText) == 0x0004B8, "Member 'UWBP_GammaStepper_C::GammaText' has a wrong offset!");

}

