#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChat

#include "Basic.hpp"

#include "WBP_TextChat_classes.hpp"
#include "WBP_TextChat_parameters.hpp"


namespace SDK
{

// Function WBP_TextChat.WBP_TextChat_C.ExecuteUbergraph_WBP_TextChat
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChat_C::ExecuteUbergraph_WBP_TextChat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "ExecuteUbergraph_WBP_TextChat");

	Params::WBP_TextChat_C_ExecuteUbergraph_WBP_TextChat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChat.WBP_TextChat_C.OnReceivedMessageFromAnotherUser
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    IsInGame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChat_C::OnReceivedMessageFromAnotherUser(bool IsInGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "OnReceivedMessageFromAnotherUser");

	Params::WBP_TextChat_C_OnReceivedMessageFromAnotherUser Parms{};

	Parms.IsInGame = IsInGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChat.WBP_TextChat_C.SetVisualState
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChat_C::SetVisualState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "SetVisualState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnAreaClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_TextChat_C::BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnAreaClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnAreaClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.AutoHideTextChat
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChat_C::AutoHideTextChat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "AutoHideTextChat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.HideChatContainer
// (BlueprintCallable, BlueprintEvent)

void UWBP_TextChat_C::HideChatContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "HideChatContainer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.OnTextChatStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMCCUITextChatOverlayState              NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChat_C::OnTextChatStateChanged(EMCCUITextChatOverlayState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "OnTextChatStateChanged");

	Params::WBP_TextChat_C_OnTextChatStateChanged Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChat.WBP_TextChat_C.OnTextChatChannelChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMCCUITextChatChannel                   NewChannel                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChat_C::OnTextChatChannelChanged(EMCCUITextChatChannel NewChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "OnTextChatChannelChanged");

	Params::WBP_TextChat_C_OnTextChatChannelChanged Parms{};

	Parms.NewChannel = NewChannel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChat.WBP_TextChat_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_TextChat_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.OnInputTextChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    IsEmptyOrWhitespace                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_TextChat_C::OnInputTextChanged(const class FText& InText, bool IsEmptyOrWhitespace)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "OnInputTextChanged");

	Params::WBP_TextChat_C_OnInputTextChanged Parms{};

	Parms.InText = std::move(InText);
	Parms.IsEmptyOrWhitespace = IsEmptyOrWhitespace;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChat.WBP_TextChat_C.SetChannelBasedColors
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TextChat_C::SetChannelBasedColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "SetChannelBasedColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChat.WBP_TextChat_C.Get_SendButton_AccessibleText
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TextChat_C::Get_SendButton_AccessibleText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "Get_SendButton_AccessibleText");

	Params::WBP_TextChat_C_Get_SendButton_AccessibleText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChat.WBP_TextChat_C.Get_CloseBox_AccessibleText
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TextChat_C::Get_CloseBox_AccessibleText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "Get_CloseBox_AccessibleText");

	Params::WBP_TextChat_C_Get_CloseBox_AccessibleText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChat.WBP_TextChat_C.Get_InputBox_AccessibleText_0
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TextChat_C::Get_InputBox_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChat_C", "Get_InputBox_AccessibleText_0");

	Params::WBP_TextChat_C_Get_InputBox_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

