#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PremiumStore

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PremiumStore.WBP_PremiumStore_C
// 0x0030 (0x0378 - 0x0348)
class UWBP_PremiumStore_C final : public UMCCPremiumStoreWidget
{
public:
	class UWBP_StoreDoubleItemBundle_C*           WBP_StoreDoubleItemBundle;                         // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StoreDoubleItemBundle_C*           WBP_StoreDoubleItemBundle_0;                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StoreMultiItemBundle_C*            WBP_StoreMultiItemBundle;                          // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StoreMultiItemBundle_C*            WBP_StoreMultiItemBundle_0;                        // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StoreSingleItemBundle_C*           WBP_StoreSingleItemBundle;                         // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StoreSingleItemBundle_C*           WBP_StoreSingleItemBundle_2;                       // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PremiumStore_C">();
	}
	static class UWBP_PremiumStore_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PremiumStore_C>();
	}
};
static_assert(alignof(UWBP_PremiumStore_C) == 0x000008, "Wrong alignment on UWBP_PremiumStore_C");
static_assert(sizeof(UWBP_PremiumStore_C) == 0x000378, "Wrong size on UWBP_PremiumStore_C");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreDoubleItemBundle) == 0x000348, "Member 'UWBP_PremiumStore_C::WBP_StoreDoubleItemBundle' has a wrong offset!");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreDoubleItemBundle_0) == 0x000350, "Member 'UWBP_PremiumStore_C::WBP_StoreDoubleItemBundle_0' has a wrong offset!");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreMultiItemBundle) == 0x000358, "Member 'UWBP_PremiumStore_C::WBP_StoreMultiItemBundle' has a wrong offset!");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreMultiItemBundle_0) == 0x000360, "Member 'UWBP_PremiumStore_C::WBP_StoreMultiItemBundle_0' has a wrong offset!");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreSingleItemBundle) == 0x000368, "Member 'UWBP_PremiumStore_C::WBP_StoreSingleItemBundle' has a wrong offset!");
static_assert(offsetof(UWBP_PremiumStore_C, WBP_StoreSingleItemBundle_2) == 0x000370, "Member 'UWBP_PremiumStore_C::WBP_StoreSingleItemBundle_2' has a wrong offset!");

}

