#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCInputDialogBoxButton

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCInputDialogBoxButton.WBP_MCCInputDialogBoxButton_C
// 0x0000 (0x0338 - 0x0338)
class UWBP_MCCInputDialogBoxButton_C final : public UMCCDialogBoxButtonWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCInputDialogBoxButton_C">();
	}
	static class UWBP_MCCInputDialogBoxButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCInputDialogBoxButton_C>();
	}
};
static_assert(alignof(UWBP_MCCInputDialogBoxButton_C) == 0x000008, "Wrong alignment on UWBP_MCCInputDialogBoxButton_C");
static_assert(sizeof(UWBP_MCCInputDialogBoxButton_C) == 0x000338, "Wrong size on UWBP_MCCInputDialogBoxButton_C");

}

