#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonTabLine

#include "Basic.hpp"

#include "WBP_SeasonTabLine_classes.hpp"
#include "WBP_SeasonTabLine_parameters.hpp"


namespace SDK
{

// Function WBP_SeasonTabLine.WBP_SeasonTabLine_C.ExecuteUbergraph_WBP_SeasonTabLine
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonTabLine_C::ExecuteUbergraph_WBP_SeasonTabLine(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonTabLine_C", "ExecuteUbergraph_WBP_SeasonTabLine");

	Params::WBP_SeasonTabLine_C_ExecuteUbergraph_WBP_SeasonTabLine Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonTabLine.WBP_SeasonTabLine_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_SeasonTabLine_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonTabLine_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

