#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMenuButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCMenuButton.WBP_MCCMenuButton_C
// 0x0028 (0x0570 - 0x0548)
class UWBP_MCCMenuButton_C final : public UMCCBaseButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0548(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Stagger;                                           // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FlickerAnimation;                                  // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectAnimation;                                   // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       GlowAnimation;                                     // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCMenuButton(int32 EntryPoint);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void PreConstruct(bool IsDesignTime);
	void OnContextChanged();
	void OnUnfocusedEvent();
	void OnFocusedEvent();
	void OnClickedEvent();
	class FText GetAccessibleText_0();
	void ToggleFocusedImageFocus(ESlateVisibility Visibility_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCMenuButton_C">();
	}
	static class UWBP_MCCMenuButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCMenuButton_C>();
	}
};
static_assert(alignof(UWBP_MCCMenuButton_C) == 0x000008, "Wrong alignment on UWBP_MCCMenuButton_C");
static_assert(sizeof(UWBP_MCCMenuButton_C) == 0x000570, "Wrong size on UWBP_MCCMenuButton_C");
static_assert(offsetof(UWBP_MCCMenuButton_C, UberGraphFrame) == 0x000548, "Member 'UWBP_MCCMenuButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMenuButton_C, Stagger) == 0x000550, "Member 'UWBP_MCCMenuButton_C::Stagger' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMenuButton_C, FlickerAnimation) == 0x000558, "Member 'UWBP_MCCMenuButton_C::FlickerAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMenuButton_C, SelectAnimation) == 0x000560, "Member 'UWBP_MCCMenuButton_C::SelectAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMenuButton_C, GlowAnimation) == 0x000568, "Member 'UWBP_MCCMenuButton_C::GlowAnimation' has a wrong offset!");

}

