#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BackgroundCustomizationScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_BackgroundCustomizationScreen.WBP_BackgroundCustomizationScreen_C
// 0x0048 (0x0400 - 0x03B8)
class UWBP_BackgroundCustomizationScreen_C final : public UMCCBackgroundCustomizationScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TitleEntry;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BackgroundCustomizationGridItem_C* WBP_BackgroundCustomizationGridItem;               // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BackgroundCustomizationGridItem_C* WBP_BackgroundCustomizationGridItem_0;             // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BackgroundCustomizationGridItem_C* WBP_BackgroundCustomizationGridItem_1;             // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BackgroundCustomizationGridItem_C* WBP_BackgroundCustomizationGridItem_2;             // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GridSplitter_C*                    WBP_GridSplitter;                                  // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PanelWidgetNavigation_C*           WBP_PanelWidgetNavigation;                         // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BackgroundCustomizationScreen(int32 EntryPoint);
	void OnContextChanged();
	void OnEnterEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_BackgroundCustomizationScreen_C">();
	}
	static class UWBP_BackgroundCustomizationScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BackgroundCustomizationScreen_C>();
	}
};
static_assert(alignof(UWBP_BackgroundCustomizationScreen_C) == 0x000008, "Wrong alignment on UWBP_BackgroundCustomizationScreen_C");
static_assert(sizeof(UWBP_BackgroundCustomizationScreen_C) == 0x000400, "Wrong size on UWBP_BackgroundCustomizationScreen_C");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, UberGraphFrame) == 0x0003B8, "Member 'UWBP_BackgroundCustomizationScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, TitleEntry) == 0x0003C0, "Member 'UWBP_BackgroundCustomizationScreen_C::TitleEntry' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_BackgroundCustomizationGridItem) == 0x0003C8, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_BackgroundCustomizationGridItem' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_BackgroundCustomizationGridItem_0) == 0x0003D0, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_BackgroundCustomizationGridItem_0' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_BackgroundCustomizationGridItem_1) == 0x0003D8, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_BackgroundCustomizationGridItem_1' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_BackgroundCustomizationGridItem_2) == 0x0003E0, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_BackgroundCustomizationGridItem_2' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_GridSplitter) == 0x0003E8, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_GridSplitter' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_PanelWidgetNavigation) == 0x0003F0, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_PanelWidgetNavigation' has a wrong offset!");
static_assert(offsetof(UWBP_BackgroundCustomizationScreen_C, WBP_ScreenTitle) == 0x0003F8, "Member 'UWBP_BackgroundCustomizationScreen_C::WBP_ScreenTitle' has a wrong offset!");

}

