#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonUnlockItemsPopup

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_SeasonUnlockItemsPopup.WBP_SeasonUnlockItemsPopup_C.ExecuteUbergraph_WBP_SeasonUnlockItemsPopup
// 0x0004 (0x0004 - 0x0000)
struct WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup) == 0x000004, "Wrong alignment on WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup");
static_assert(sizeof(WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup) == 0x000004, "Wrong size on WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup");
static_assert(offsetof(WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup, EntryPoint) == 0x000000, "Member 'WBP_SeasonUnlockItemsPopup_C_ExecuteUbergraph_WBP_SeasonUnlockItemsPopup::EntryPoint' has a wrong offset!");

}

