#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCInputDialogBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCInputDialogBox.WBP_MCCInputDialogBox_C
// 0x0040 (0x0528 - 0x04E8)
class UWBP_MCCInputDialogBox_C final : public UMCCDialogBoxWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       MoveUp;                                            // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeIn;                                            // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 backgound;                                         // 0x0500(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Backing;                                           // 0x0508(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TitleImage;                                        // 0x0510(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCInputDialogBoxButton_C*         WBP_MCCInputDialogBoxButton;                       // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCInputDialogBoxButton_C*         WBP_MCCInputDialogBoxButton_1;                     // 0x0520(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCInputDialogBox(int32 EntryPoint);
	void OnContextChanged();
	void OnEnterEvent();
	void OnExitEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCInputDialogBox_C">();
	}
	static class UWBP_MCCInputDialogBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCInputDialogBox_C>();
	}
};
static_assert(alignof(UWBP_MCCInputDialogBox_C) == 0x000008, "Wrong alignment on UWBP_MCCInputDialogBox_C");
static_assert(sizeof(UWBP_MCCInputDialogBox_C) == 0x000528, "Wrong size on UWBP_MCCInputDialogBox_C");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, UberGraphFrame) == 0x0004E8, "Member 'UWBP_MCCInputDialogBox_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, MoveUp) == 0x0004F0, "Member 'UWBP_MCCInputDialogBox_C::MoveUp' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, FadeIn) == 0x0004F8, "Member 'UWBP_MCCInputDialogBox_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, backgound) == 0x000500, "Member 'UWBP_MCCInputDialogBox_C::backgound' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, Backing) == 0x000508, "Member 'UWBP_MCCInputDialogBox_C::Backing' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, TitleImage) == 0x000510, "Member 'UWBP_MCCInputDialogBox_C::TitleImage' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, WBP_MCCInputDialogBoxButton) == 0x000518, "Member 'UWBP_MCCInputDialogBox_C::WBP_MCCInputDialogBoxButton' has a wrong offset!");
static_assert(offsetof(UWBP_MCCInputDialogBox_C, WBP_MCCInputDialogBoxButton_1) == 0x000520, "Member 'UWBP_MCCInputDialogBox_C::WBP_MCCInputDialogBoxButton_1' has a wrong offset!");

}

