#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonTierTile

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "MCC_structs.hpp"


namespace SDK::Params
{

// Function WBP_SeasonTierTile.WBP_SeasonTierTile_C.ExecuteUbergraph_WBP_SeasonTierTile
// 0x0018 (0x0018 - 0x0000)
struct WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent1;                        // 0x0004(0x0008)(NoDestructor)
	EMCCUIRewardTierStatus                        CallFunc_GetStatus_ReturnValue;                    // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0010(0x0008)(NoDestructor)
};
static_assert(alignof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile) == 0x000004, "Wrong alignment on WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile");
static_assert(sizeof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile) == 0x000018, "Wrong size on WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile");
static_assert(offsetof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile, EntryPoint) == 0x000000, "Member 'WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile, K2Node_Event_InFocusEvent1) == 0x000004, "Member 'WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile::K2Node_Event_InFocusEvent1' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile, CallFunc_GetStatus_ReturnValue) == 0x00000C, "Member 'WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile::CallFunc_GetStatus_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile, K2Node_SwitchEnum_CmpSuccess) == 0x00000D, "Member 'WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile, K2Node_Event_InFocusEvent) == 0x000010, "Member 'WBP_SeasonTierTile_C_ExecuteUbergraph_WBP_SeasonTierTile::K2Node_Event_InFocusEvent' has a wrong offset!");

// Function WBP_SeasonTierTile.WBP_SeasonTierTile_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_SeasonTierTile_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_SeasonTierTile_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on WBP_SeasonTierTile_C_OnRemovedFromFocusPath");
static_assert(sizeof(WBP_SeasonTierTile_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on WBP_SeasonTierTile_C_OnRemovedFromFocusPath");
static_assert(offsetof(WBP_SeasonTierTile_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_SeasonTierTile_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_SeasonTierTile.WBP_SeasonTierTile_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_SeasonTierTile_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_SeasonTierTile_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on WBP_SeasonTierTile_C_OnAddedToFocusPath");
static_assert(sizeof(WBP_SeasonTierTile_C_OnAddedToFocusPath) == 0x000008, "Wrong size on WBP_SeasonTierTile_C_OnAddedToFocusPath");
static_assert(offsetof(WBP_SeasonTierTile_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_SeasonTierTile_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_SeasonTierTile.WBP_SeasonTierTile_C.SetOpacity
// 0x0004 (0x0004 - 0x0000)
struct WBP_SeasonTierTile_C_SetOpacity final
{
public:
	float                                         InOpacity;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_SeasonTierTile_C_SetOpacity) == 0x000004, "Wrong alignment on WBP_SeasonTierTile_C_SetOpacity");
static_assert(sizeof(WBP_SeasonTierTile_C_SetOpacity) == 0x000004, "Wrong size on WBP_SeasonTierTile_C_SetOpacity");
static_assert(offsetof(WBP_SeasonTierTile_C_SetOpacity, InOpacity) == 0x000000, "Member 'WBP_SeasonTierTile_C_SetOpacity::InOpacity' has a wrong offset!");

// Function WBP_SeasonTierTile.WBP_SeasonTierTile_C.Get_InteractiveWidget_AccessibleText_0
// 0x0098 (0x0098 - 0x0000)
struct WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0028(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue1;               // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue2;               // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue3;               // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0080(0x0018)()
};
static_assert(alignof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0");
static_assert(sizeof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0) == 0x000098, "Wrong size on WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue) == 0x000018, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_GetText_ReturnValue) == 0x000028, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Conv_TextToString_ReturnValue) == 0x000040, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue1) == 0x000050, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue2) == 0x000060, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue2' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue3) == 0x000070, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue3' has a wrong offset!");
static_assert(offsetof(WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0, CallFunc_Conv_StringToText_ReturnValue) == 0x000080, "Member 'WBP_SeasonTierTile_C_Get_InteractiveWidget_AccessibleText_0::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

