#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationTab

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_CustomizationTab.WBP_CustomizationTab_C.ExecuteUbergraph_WBP_CustomizationTab
// 0x0018 (0x0018 - 0x0000)
struct WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsSelected;                           // 0x0005(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UMCCCustomizationTabViewModel*          K2Node_DynamicCast_AsMCCCustomization_Tab_View_Model; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab) == 0x000008, "Wrong alignment on WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab");
static_assert(sizeof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab) == 0x000018, "Wrong size on WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab");
static_assert(offsetof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab, EntryPoint) == 0x000000, "Member 'WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab, K2Node_Event_IsSelected) == 0x000005, "Member 'WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab::K2Node_Event_IsSelected' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab, K2Node_DynamicCast_AsMCCCustomization_Tab_View_Model) == 0x000008, "Member 'WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab::K2Node_DynamicCast_AsMCCCustomization_Tab_View_Model' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'WBP_CustomizationTab_C_ExecuteUbergraph_WBP_CustomizationTab::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_CustomizationTab.WBP_CustomizationTab_C.UpdateSelection
// 0x0001 (0x0001 - 0x0000)
struct WBP_CustomizationTab_C_UpdateSelection final
{
public:
	bool                                          IsSelected;                                        // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_CustomizationTab_C_UpdateSelection) == 0x000001, "Wrong alignment on WBP_CustomizationTab_C_UpdateSelection");
static_assert(sizeof(WBP_CustomizationTab_C_UpdateSelection) == 0x000001, "Wrong size on WBP_CustomizationTab_C_UpdateSelection");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelection, IsSelected) == 0x000000, "Member 'WBP_CustomizationTab_C_UpdateSelection::IsSelected' has a wrong offset!");

// Function WBP_CustomizationTab.WBP_CustomizationTab_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_CustomizationTab_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_CustomizationTab_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_CustomizationTab_C_PreConstruct");
static_assert(sizeof(WBP_CustomizationTab_C_PreConstruct) == 0x000001, "Wrong size on WBP_CustomizationTab_C_PreConstruct");
static_assert(offsetof(WBP_CustomizationTab_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_CustomizationTab_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_CustomizationTab.WBP_CustomizationTab_C.UpdateSelectedVisuals
// 0x0078 (0x0078 - 0x0000)
struct WBP_CustomizationTab_C_UpdateSelectedVisuals final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Selected;                                          // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable1;                               // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable2;                               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MakeLiteralFloat_ReturnValue;             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeLiteralFloat_ReturnValue1;            // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FColor                                 CallFunc_Conv_LinearColorToColor_ReturnValue;      // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select1_Default;                            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_Conv_ColorToLinearColor_ReturnValue;      // 0x001C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByThemeName_ReturnValue;          // 0x002C(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select2_Default;                            // 0x003C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0050(0x0028)()
};
static_assert(alignof(WBP_CustomizationTab_C_UpdateSelectedVisuals) == 0x000008, "Wrong alignment on WBP_CustomizationTab_C_UpdateSelectedVisuals");
static_assert(sizeof(WBP_CustomizationTab_C_UpdateSelectedVisuals) == 0x000078, "Wrong size on WBP_CustomizationTab_C_UpdateSelectedVisuals");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, bIsSelected) == 0x000000, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::bIsSelected' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Selected) == 0x000001, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Selected' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Temp_bool_Variable) == 0x000002, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Temp_bool_Variable1) == 0x000003, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Temp_bool_Variable2) == 0x000004, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Temp_byte_Variable) == 0x000005, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, Temp_byte_Variable1) == 0x000006, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, CallFunc_MakeLiteralFloat_ReturnValue) == 0x000008, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::CallFunc_MakeLiteralFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, CallFunc_MakeLiteralFloat_ReturnValue1) == 0x00000C, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::CallFunc_MakeLiteralFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, K2Node_Select_Default) == 0x000010, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, CallFunc_Conv_LinearColorToColor_ReturnValue) == 0x000014, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::CallFunc_Conv_LinearColorToColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, K2Node_Select1_Default) == 0x000018, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, CallFunc_Conv_ColorToLinearColor_ReturnValue) == 0x00001C, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::CallFunc_Conv_ColorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, CallFunc_GetColorByThemeName_ReturnValue) == 0x00002C, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::CallFunc_GetColorByThemeName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, K2Node_Select2_Default) == 0x00003C, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationTab_C_UpdateSelectedVisuals, K2Node_MakeStruct_SlateColor) == 0x000050, "Member 'WBP_CustomizationTab_C_UpdateSelectedVisuals::K2Node_MakeStruct_SlateColor' has a wrong offset!");

// Function WBP_CustomizationTab.WBP_CustomizationTab_C.Get_ButtonTile_AccessibleText_0
// 0x0018 (0x0018 - 0x0000)
struct WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0");
static_assert(sizeof(WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0) == 0x000018, "Wrong size on WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0");
static_assert(offsetof(WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_CustomizationTab_C_Get_ButtonTile_AccessibleText_0::ReturnValue' has a wrong offset!");

}

