#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BackgroundSelectionButton

#include "Basic.hpp"

#include "WBP_BackgroundSelectionButton_classes.hpp"
#include "WBP_BackgroundSelectionButton_parameters.hpp"


namespace SDK
{

// Function WBP_BackgroundSelectionButton.WBP_BackgroundSelectionButton_C.GetAccessibleText_0
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_BackgroundSelectionButton_C::GetAccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BackgroundSelectionButton_C", "GetAccessibleText_0");

	Params::WBP_BackgroundSelectionButton_C_GetAccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

