#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMatchmakingFirefightScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCMatchmakingFirefightScreen.WBP_MCCMatchmakingFirefightScreen_C
// 0x00B8 (0x0508 - 0x0450)
class UWBP_MCCMatchmakingFirefightScreen_C final : public UMCCMatchmakingFirefightScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ListEntry;                                         // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       BreadcrumbEntry;                                   // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       TitleEntry;                                        // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton;                                 // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_0;                               // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_1;                               // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_2;                               // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_3;                               // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_4;                               // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_5;                               // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_6;                               // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_7;                               // 0x04C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_8;                               // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_9;                               // 0x04D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMenuButton_C*                   WBP_MCCMenuButton_10;                              // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x04E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         Option_Counter;                                    // 0x04F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4F4[0x4];                                      // 0x04F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBox*                           VerticalMenuOptions;                               // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         StaggerAnimationDelay;                             // 0x0500(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCMatchmakingFirefightScreen(int32 EntryPoint);
	void OnContextChanged();
	void OnEnterEvent();
	void PlayAnimStagger();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCMatchmakingFirefightScreen_C">();
	}
	static class UWBP_MCCMatchmakingFirefightScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCMatchmakingFirefightScreen_C>();
	}
};
static_assert(alignof(UWBP_MCCMatchmakingFirefightScreen_C) == 0x000008, "Wrong alignment on UWBP_MCCMatchmakingFirefightScreen_C");
static_assert(sizeof(UWBP_MCCMatchmakingFirefightScreen_C) == 0x000508, "Wrong size on UWBP_MCCMatchmakingFirefightScreen_C");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, UberGraphFrame) == 0x000450, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, ListEntry) == 0x000458, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::ListEntry' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, BreadcrumbEntry) == 0x000460, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::BreadcrumbEntry' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, TitleEntry) == 0x000468, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::TitleEntry' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, Image_0) == 0x000470, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, Image_2) == 0x000478, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::Image_2' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, Image_3) == 0x000480, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::Image_3' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton) == 0x000488, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_0) == 0x000490, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_0' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_1) == 0x000498, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_1' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_2) == 0x0004A0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_2' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_3) == 0x0004A8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_3' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_4) == 0x0004B0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_4' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_5) == 0x0004B8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_5' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_6) == 0x0004C0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_6' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_7) == 0x0004C8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_7' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_8) == 0x0004D0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_8' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_9) == 0x0004D8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_9' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_MCCMenuButton_10) == 0x0004E0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_MCCMenuButton_10' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, WBP_ScreenTitle) == 0x0004E8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::WBP_ScreenTitle' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, Option_Counter) == 0x0004F0, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::Option_Counter' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, VerticalMenuOptions) == 0x0004F8, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::VerticalMenuOptions' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMatchmakingFirefightScreen_C, StaggerAnimationDelay) == 0x000500, "Member 'UWBP_MCCMatchmakingFirefightScreen_C::StaggerAnimationDelay' has a wrong offset!");

}

