#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionDropdownButton

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_OptionDropdownButton.WBP_OptionDropdownButton_C.ExecuteUbergraph_WBP_OptionDropdownButton
// 0x0008 (0x0008 - 0x0000)
struct WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_UserIndex;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton) == 0x000004, "Wrong alignment on WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton");
static_assert(sizeof(WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton) == 0x000008, "Wrong size on WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton");
static_assert(offsetof(WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton, EntryPoint) == 0x000000, "Member 'WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton, K2Node_ComponentBoundEvent_UserIndex) == 0x000004, "Member 'WBP_OptionDropdownButton_C_ExecuteUbergraph_WBP_OptionDropdownButton::K2Node_ComponentBoundEvent_UserIndex' has a wrong offset!");

// Function WBP_OptionDropdownButton.WBP_OptionDropdownButton_C.BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature final
{
public:
	int32                                         UserIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature");
static_assert(sizeof(WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature");
static_assert(offsetof(WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature, UserIndex) == 0x000000, "Member 'WBP_OptionDropdownButton_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetClickedEvent__DelegateSignature::UserIndex' has a wrong offset!");

// Function WBP_OptionDropdownButton.WBP_OptionDropdownButton_C.Get_ButtonText_AccessibleText_0
// 0x0030 (0x0030 - 0x0000)
struct WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0018(0x0018)()
};
static_assert(alignof(WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0");
static_assert(sizeof(WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0) == 0x000030, "Wrong size on WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0");
static_assert(offsetof(WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0, CallFunc_GetText_ReturnValue) == 0x000018, "Member 'WBP_OptionDropdownButton_C_Get_ButtonText_AccessibleText_0::CallFunc_GetText_ReturnValue' has a wrong offset!");

}

