#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Tab.WBP_Tab_C
// 0x0038 (0x05B8 - 0x0580)
class UWBP_Tab_C final : public UMCCTabWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0580(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TabSelected;                                       // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Line;                                              // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Text;                                              // 0x0598(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   SelectionName;                                     // 0x05A0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_WBP_Tab(int32 EntryPoint);
	void UpdateSelection(const bool IsSelected);
	void OnContextChanged();
	void PreConstruct(bool IsDesignTime);
	void UpdateSelectedVisuals(bool bIsSelected);
	class FText Get_ButtonTile_AccessibleText_0();
	void Get_InteractiveArea_AccessibleText_0();
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Tab_C">();
	}
	static class UWBP_Tab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Tab_C>();
	}
};
static_assert(alignof(UWBP_Tab_C) == 0x000008, "Wrong alignment on UWBP_Tab_C");
static_assert(sizeof(UWBP_Tab_C) == 0x0005B8, "Wrong size on UWBP_Tab_C");
static_assert(offsetof(UWBP_Tab_C, UberGraphFrame) == 0x000580, "Member 'UWBP_Tab_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Tab_C, TabSelected) == 0x000588, "Member 'UWBP_Tab_C::TabSelected' has a wrong offset!");
static_assert(offsetof(UWBP_Tab_C, Line) == 0x000590, "Member 'UWBP_Tab_C::Line' has a wrong offset!");
static_assert(offsetof(UWBP_Tab_C, Text) == 0x000598, "Member 'UWBP_Tab_C::Text' has a wrong offset!");
static_assert(offsetof(UWBP_Tab_C, SelectionName) == 0x0005A0, "Member 'UWBP_Tab_C::SelectionName' has a wrong offset!");

}

