#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMultiplayerCustomGamesBrowse

#include "Basic.hpp"

#include "WBP_MCCMultiplayerCustomGamesBrowse_classes.hpp"
#include "WBP_MCCMultiplayerCustomGamesBrowse_parameters.hpp"


namespace SDK
{

// Function WBP_MCCMultiplayerCustomGamesBrowse.WBP_MCCMultiplayerCustomGamesBrowse_C.ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowse
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCMultiplayerCustomGamesBrowse_C::ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowse(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesBrowse_C", "ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowse");

	Params::WBP_MCCMultiplayerCustomGamesBrowse_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowse Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCMultiplayerCustomGamesBrowse.WBP_MCCMultiplayerCustomGamesBrowse_C.Get_SearchInteractiveArea_AccessibleText_0
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_MCCMultiplayerCustomGamesBrowse_C::Get_SearchInteractiveArea_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesBrowse_C", "Get_SearchInteractiveArea_AccessibleText_0");

	Params::WBP_MCCMultiplayerCustomGamesBrowse_C_Get_SearchInteractiveArea_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MCCMultiplayerCustomGamesBrowse.WBP_MCCMultiplayerCustomGamesBrowse_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_MCCMultiplayerCustomGamesBrowse_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesBrowse_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

