#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayFabCurrencyReward

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayFabCurrencyReward.WBP_PlayFabCurrencyReward_C
// 0x0020 (0x0360 - 0x0340)
class UWBP_PlayFabCurrencyReward_C final : public UMCCPlayFabRewardWidget
{
public:
	class UMCCUUIImage*                           FullHorizontalFrame;                               // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           FullHorizontalInsideFrame;                         // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           HorizontalFiller;                                  // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           ItemBGGradient;                                    // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PlayFabCurrencyReward_C">();
	}
	static class UWBP_PlayFabCurrencyReward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayFabCurrencyReward_C>();
	}
};
static_assert(alignof(UWBP_PlayFabCurrencyReward_C) == 0x000008, "Wrong alignment on UWBP_PlayFabCurrencyReward_C");
static_assert(sizeof(UWBP_PlayFabCurrencyReward_C) == 0x000360, "Wrong size on UWBP_PlayFabCurrencyReward_C");
static_assert(offsetof(UWBP_PlayFabCurrencyReward_C, FullHorizontalFrame) == 0x000340, "Member 'UWBP_PlayFabCurrencyReward_C::FullHorizontalFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PlayFabCurrencyReward_C, FullHorizontalInsideFrame) == 0x000348, "Member 'UWBP_PlayFabCurrencyReward_C::FullHorizontalInsideFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PlayFabCurrencyReward_C, HorizontalFiller) == 0x000350, "Member 'UWBP_PlayFabCurrencyReward_C::HorizontalFiller' has a wrong offset!");
static_assert(offsetof(UWBP_PlayFabCurrencyReward_C, ItemBGGradient) == 0x000358, "Member 'UWBP_PlayFabCurrencyReward_C::ItemBGGradient' has a wrong offset!");

}

