#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCPlayerButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCPlayerButton.WBP_MCCPlayerButton_C
// 0x0090 (0x0400 - 0x0370)
class UWBP_MCCPlayerButton_C final : public UMCCSessionPlayerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       MoveAnimation;                                     // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectionAnimation;                                // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               ClanTagName;                                       // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FocusedImage;                                      // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconChatState;                                     // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconPlayerState;                                   // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               LeftBracket;                                       // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         NameplateContainer;                                // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 OwnPlayerImage;                                    // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           RankImage;                                         // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               RankImageSizeBox;                                  // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               RightBracket;                                      // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SteamFriendIconContainer;                          // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TeamPip;                                           // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               TeamPipContainer;                                  // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                TeamPipSpacer;                                     // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCPlayerButtonPrompt_C*           WBP_MCCPlayerButtonPrompt;                         // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCPlayerButton(int32 EntryPoint);
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_0_OnWidgetReleasedEvent__DelegateSignature();
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_1_OnWidgetPressedEvent__DelegateSignature();
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_2_OnWidgetFocusLostEvent__DelegateSignature();
	void ApplyTeamColor(const struct FLinearColor& TeamColor);
	void OnContextChanged();
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_6_OnWidgetClickedEvent__DelegateSignature(int32 UserIndex);
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_5_OnWidgetHoverEvent__DelegateSignature();
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_4_OnWidgetHoverEvent__DelegateSignature();
	void BndEvt__SDWidget_0_K2Node_ComponentBoundEvent_3_OnWidgetFocusReceivedEvent__DelegateSignature();
	void ShowReleased();
	void ShowPressed();
	void ShowSelected(bool IsSelected);
	class FText Get_InteractiveArea_AccessibleText();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCPlayerButton_C">();
	}
	static class UWBP_MCCPlayerButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCPlayerButton_C>();
	}
};
static_assert(alignof(UWBP_MCCPlayerButton_C) == 0x000008, "Wrong alignment on UWBP_MCCPlayerButton_C");
static_assert(sizeof(UWBP_MCCPlayerButton_C) == 0x000400, "Wrong size on UWBP_MCCPlayerButton_C");
static_assert(offsetof(UWBP_MCCPlayerButton_C, UberGraphFrame) == 0x000370, "Member 'UWBP_MCCPlayerButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, MoveAnimation) == 0x000378, "Member 'UWBP_MCCPlayerButton_C::MoveAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, SelectionAnimation) == 0x000380, "Member 'UWBP_MCCPlayerButton_C::SelectionAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, ClanTagName) == 0x000388, "Member 'UWBP_MCCPlayerButton_C::ClanTagName' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, FocusedImage) == 0x000390, "Member 'UWBP_MCCPlayerButton_C::FocusedImage' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, IconChatState) == 0x000398, "Member 'UWBP_MCCPlayerButton_C::IconChatState' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, IconPlayerState) == 0x0003A0, "Member 'UWBP_MCCPlayerButton_C::IconPlayerState' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, LeftBracket) == 0x0003A8, "Member 'UWBP_MCCPlayerButton_C::LeftBracket' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, NameplateContainer) == 0x0003B0, "Member 'UWBP_MCCPlayerButton_C::NameplateContainer' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, OwnPlayerImage) == 0x0003B8, "Member 'UWBP_MCCPlayerButton_C::OwnPlayerImage' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, RankImage) == 0x0003C0, "Member 'UWBP_MCCPlayerButton_C::RankImage' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, RankImageSizeBox) == 0x0003C8, "Member 'UWBP_MCCPlayerButton_C::RankImageSizeBox' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, RightBracket) == 0x0003D0, "Member 'UWBP_MCCPlayerButton_C::RightBracket' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, SteamFriendIconContainer) == 0x0003D8, "Member 'UWBP_MCCPlayerButton_C::SteamFriendIconContainer' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, TeamPip) == 0x0003E0, "Member 'UWBP_MCCPlayerButton_C::TeamPip' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, TeamPipContainer) == 0x0003E8, "Member 'UWBP_MCCPlayerButton_C::TeamPipContainer' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, TeamPipSpacer) == 0x0003F0, "Member 'UWBP_MCCPlayerButton_C::TeamPipSpacer' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButton_C, WBP_MCCPlayerButtonPrompt) == 0x0003F8, "Member 'UWBP_MCCPlayerButton_C::WBP_MCCPlayerButtonPrompt' has a wrong offset!");

}

