#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChallengeOverviewScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ChallengeOverviewScreen.WBP_ChallengeOverviewScreen_C
// 0x0040 (0x0448 - 0x0408)
class UWBP_ChallengeOverviewScreen_C final : public UMCCChallengeHubScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TitleEntry;                                        // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Challenge_C*                       WBP_Challenge;                                     // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Challenge_C*                       WBP_Challenge_0;                                   // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Challenge_C*                       WBP_Challenge_1;                                   // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Challenge_C*                       WBP_Challenge_2;                                   // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PanelWidgetNavigation_C*           WBP_PanelWidgetNavigation;                         // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ChallengeOverviewScreen(int32 EntryPoint);
	void OnContextChanged();
	void OnEnterEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ChallengeOverviewScreen_C">();
	}
	static class UWBP_ChallengeOverviewScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ChallengeOverviewScreen_C>();
	}
};
static_assert(alignof(UWBP_ChallengeOverviewScreen_C) == 0x000008, "Wrong alignment on UWBP_ChallengeOverviewScreen_C");
static_assert(sizeof(UWBP_ChallengeOverviewScreen_C) == 0x000448, "Wrong size on UWBP_ChallengeOverviewScreen_C");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, UberGraphFrame) == 0x000408, "Member 'UWBP_ChallengeOverviewScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, TitleEntry) == 0x000410, "Member 'UWBP_ChallengeOverviewScreen_C::TitleEntry' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_Challenge) == 0x000418, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_Challenge' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_Challenge_0) == 0x000420, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_Challenge_0' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_Challenge_1) == 0x000428, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_Challenge_1' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_Challenge_2) == 0x000430, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_Challenge_2' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_PanelWidgetNavigation) == 0x000438, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_PanelWidgetNavigation' has a wrong offset!");
static_assert(offsetof(UWBP_ChallengeOverviewScreen_C, WBP_ScreenTitle) == 0x000440, "Member 'UWBP_ChallengeOverviewScreen_C::WBP_ScreenTitle' has a wrong offset!");

}

