#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InstallerScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InstallerScreen.WBP_InstallerScreen_C
// 0x0028 (0x03E8 - 0x03C0)
class UWBP_InstallerScreen_C final : public UMCCInstallerScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDInputControllerWidgetSwitcher*       PriorityPrompt;                                    // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDInputControllerWidgetSwitcher*       SDInputControllerWidgetSwitcher_0;                 // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDRichTextBlock*                       SDRichTextBlock_0;                                 // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InstallerScreen(int32 EntryPoint);
	void OnEnterEvent();
	void OnContextChanged();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_InstallerScreen_C">();
	}
	static class UWBP_InstallerScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InstallerScreen_C>();
	}
};
static_assert(alignof(UWBP_InstallerScreen_C) == 0x000008, "Wrong alignment on UWBP_InstallerScreen_C");
static_assert(sizeof(UWBP_InstallerScreen_C) == 0x0003E8, "Wrong size on UWBP_InstallerScreen_C");
static_assert(offsetof(UWBP_InstallerScreen_C, UberGraphFrame) == 0x0003C0, "Member 'UWBP_InstallerScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_InstallerScreen_C, PriorityPrompt) == 0x0003C8, "Member 'UWBP_InstallerScreen_C::PriorityPrompt' has a wrong offset!");
static_assert(offsetof(UWBP_InstallerScreen_C, SDInputControllerWidgetSwitcher_0) == 0x0003D0, "Member 'UWBP_InstallerScreen_C::SDInputControllerWidgetSwitcher_0' has a wrong offset!");
static_assert(offsetof(UWBP_InstallerScreen_C, SDRichTextBlock_0) == 0x0003D8, "Member 'UWBP_InstallerScreen_C::SDRichTextBlock_0' has a wrong offset!");
static_assert(offsetof(UWBP_InstallerScreen_C, WBP_ScreenTitle) == 0x0003E0, "Member 'UWBP_InstallerScreen_C::WBP_ScreenTitle' has a wrong offset!");

}

