#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCBaseButton

#include "Basic.hpp"

#include "WBP_MCCBaseButton_classes.hpp"
#include "WBP_MCCBaseButton_parameters.hpp"


namespace SDK
{

// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.ExecuteUbergraph_WBP_MCCBaseButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCBaseButton_C::ExecuteUbergraph_WBP_MCCBaseButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "ExecuteUbergraph_WBP_MCCBaseButton");

	Params::WBP_MCCBaseButton_C_ExecuteUbergraph_WBP_MCCBaseButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnInputControllerChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ESDInputControllerType                  InInputControllerType                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCBaseButton_C::OnInputControllerChanged(ESDInputControllerType InInputControllerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnInputControllerChanged");

	Params::WBP_MCCBaseButton_C_OnInputControllerChanged Parms{};

	Parms.InInputControllerType = InInputControllerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_MCCBaseButton_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnUnhoveredEvent
// (Event, Protected, BlueprintEvent)

void UWBP_MCCBaseButton_C::OnUnhoveredEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnUnhoveredEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnUnfocusedEvent
// (Event, Protected, BlueprintEvent)

void UWBP_MCCBaseButton_C::OnUnfocusedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnUnfocusedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnHoveredEvent
// (Event, Protected, BlueprintEvent)

void UWBP_MCCBaseButton_C::OnHoveredEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnHoveredEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.OnFocusedEvent
// (Event, Protected, BlueprintEvent)

void UWBP_MCCBaseButton_C::OnFocusedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "OnFocusedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.GetAccessibleText
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_MCCBaseButton_C::GetAccessibleText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "GetAccessibleText");

	Params::WBP_MCCBaseButton_C_GetAccessibleText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.ToggleHatching
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_MCCBaseButton_C::ToggleHatching()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "ToggleHatching");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCBaseButton.WBP_MCCBaseButton_C.ToggleFocus
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visibility_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCBaseButton_C::ToggleFocus(ESlateVisibility Visibility_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCBaseButton_C", "ToggleFocus");

	Params::WBP_MCCBaseButton_C_ToggleFocus Parms{};

	Parms.Visibility_0 = Visibility_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

