#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GamepadPreviewFront

#include "Basic.hpp"

#include "WBP_GamepadPreviewFront_classes.hpp"
#include "WBP_GamepadPreviewFront_parameters.hpp"


namespace SDK
{

// Function WBP_GamepadPreviewFront.WBP_GamepadPreviewFront_C.ExecuteUbergraph_WBP_GamepadPreviewFront
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GamepadPreviewFront_C::ExecuteUbergraph_WBP_GamepadPreviewFront(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GamepadPreviewFront_C", "ExecuteUbergraph_WBP_GamepadPreviewFront");

	Params::WBP_GamepadPreviewFront_C_ExecuteUbergraph_WBP_GamepadPreviewFront Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GamepadPreviewFront.WBP_GamepadPreviewFront_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_GamepadPreviewFront_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GamepadPreviewFront_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

