#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCNotificationDialog

#include "Basic.hpp"

#include "WBP_MCCNotificationDialog_classes.hpp"
#include "WBP_MCCNotificationDialog_parameters.hpp"


namespace SDK
{

// Function WBP_MCCNotificationDialog.WBP_MCCNotificationDialog_C.ExecuteUbergraph_WBP_MCCNotificationDialog
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCNotificationDialog_C::ExecuteUbergraph_WBP_MCCNotificationDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCNotificationDialog_C", "ExecuteUbergraph_WBP_MCCNotificationDialog");

	Params::WBP_MCCNotificationDialog_C_ExecuteUbergraph_WBP_MCCNotificationDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCNotificationDialog.WBP_MCCNotificationDialog_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_MCCNotificationDialog_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCNotificationDialog_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

