#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCCloseBox

#include "Basic.hpp"

#include "WBP_MCCCloseBox_classes.hpp"
#include "WBP_MCCCloseBox_parameters.hpp"


namespace SDK
{

// Function WBP_MCCCloseBox.WBP_MCCCloseBox_C.ExecuteUbergraph_WBP_MCCCloseBox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCCloseBox_C::ExecuteUbergraph_WBP_MCCCloseBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCCloseBox_C", "ExecuteUbergraph_WBP_MCCCloseBox");

	Params::WBP_MCCCloseBox_C_ExecuteUbergraph_WBP_MCCCloseBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCCloseBox.WBP_MCCCloseBox_C.BndEvt__CloseBox_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   UserIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCCloseBox_C::BndEvt__CloseBox_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature(int32 UserIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCCloseBox_C", "BndEvt__CloseBox_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature");

	Params::WBP_MCCCloseBox_C_BndEvt__CloseBox_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature Parms{};

	Parms.UserIndex = UserIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCCloseBox.WBP_MCCCloseBox_C.BndEvt__SDTile_2_K2Node_ComponentBoundEvent_5_OnWidgetHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MCCCloseBox_C::BndEvt__SDTile_2_K2Node_ComponentBoundEvent_5_OnWidgetHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCCloseBox_C", "BndEvt__SDTile_2_K2Node_ComponentBoundEvent_5_OnWidgetHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCCloseBox.WBP_MCCCloseBox_C.BndEvt__SDTile_2_K2Node_ComponentBoundEvent_6_OnWidgetHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MCCCloseBox_C::BndEvt__SDTile_2_K2Node_ComponentBoundEvent_6_OnWidgetHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCCloseBox_C", "BndEvt__SDTile_2_K2Node_ComponentBoundEvent_6_OnWidgetHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

