#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsPreviewWidget

#include "Basic.hpp"

#include "WBP_SettingsPreviewWidget_classes.hpp"
#include "WBP_SettingsPreviewWidget_parameters.hpp"


namespace SDK
{

// Function WBP_SettingsPreviewWidget.WBP_SettingsPreviewWidget_C.ExecuteUbergraph_WBP_SettingsPreviewWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsPreviewWidget_C::ExecuteUbergraph_WBP_SettingsPreviewWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewWidget_C", "ExecuteUbergraph_WBP_SettingsPreviewWidget");

	Params::WBP_SettingsPreviewWidget_C_ExecuteUbergraph_WBP_SettingsPreviewWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsPreviewWidget.WBP_SettingsPreviewWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_SettingsPreviewWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsPreviewWidget.WBP_SettingsPreviewWidget_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_SettingsPreviewWidget_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewWidget_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsPreviewWidget.WBP_SettingsPreviewWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsPreviewWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsPreviewWidget_C", "Tick");

	Params::WBP_SettingsPreviewWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

