#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCBreadcrumbEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCBreadcrumbEntry.WBP_MCCBreadcrumbEntry_C
// 0x0010 (0x0340 - 0x0330)
class UWBP_MCCBreadcrumbEntry_C final : public UMCCBreadcrumbEntryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDConfigurableTextBlock*               BreadcrumbText;                                    // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCBreadcrumbEntry(int32 EntryPoint);
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCBreadcrumbEntry_C">();
	}
	static class UWBP_MCCBreadcrumbEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCBreadcrumbEntry_C>();
	}
};
static_assert(alignof(UWBP_MCCBreadcrumbEntry_C) == 0x000008, "Wrong alignment on UWBP_MCCBreadcrumbEntry_C");
static_assert(sizeof(UWBP_MCCBreadcrumbEntry_C) == 0x000340, "Wrong size on UWBP_MCCBreadcrumbEntry_C");
static_assert(offsetof(UWBP_MCCBreadcrumbEntry_C, UberGraphFrame) == 0x000330, "Member 'UWBP_MCCBreadcrumbEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCBreadcrumbEntry_C, BreadcrumbText) == 0x000338, "Member 'UWBP_MCCBreadcrumbEntry_C::BreadcrumbText' has a wrong offset!");

}

