#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionInputBindingDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_OptionInputBindingDisplay.WBP_OptionInputBindingDisplay_C
// 0x0018 (0x04A8 - 0x0490)
class UWBP_OptionInputBindingDisplay_C final : public UMCCOptionInputBindingDisplayWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDConfigurableTextBlock*               InputTextPrimary;                                  // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                MissingBindingBorder;                              // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_OptionInputBindingDisplay(int32 EntryPoint);
	class FText Get_PrimaryBinding_AccessibleText_0();
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_OptionInputBindingDisplay_C">();
	}
	static class UWBP_OptionInputBindingDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OptionInputBindingDisplay_C>();
	}
};
static_assert(alignof(UWBP_OptionInputBindingDisplay_C) == 0x000008, "Wrong alignment on UWBP_OptionInputBindingDisplay_C");
static_assert(sizeof(UWBP_OptionInputBindingDisplay_C) == 0x0004A8, "Wrong size on UWBP_OptionInputBindingDisplay_C");
static_assert(offsetof(UWBP_OptionInputBindingDisplay_C, UberGraphFrame) == 0x000490, "Member 'UWBP_OptionInputBindingDisplay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_OptionInputBindingDisplay_C, InputTextPrimary) == 0x000498, "Member 'UWBP_OptionInputBindingDisplay_C::InputTextPrimary' has a wrong offset!");
static_assert(offsetof(UWBP_OptionInputBindingDisplay_C, MissingBindingBorder) == 0x0004A0, "Member 'UWBP_OptionInputBindingDisplay_C::MissingBindingBorder' has a wrong offset!");

}

