#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMultiplayerCustomGamesBrowse

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCMultiplayerCustomGamesBrowse.WBP_MCCMultiplayerCustomGamesBrowse_C
// 0x0058 (0x04B8 - 0x0460)
class UWBP_MCCMultiplayerCustomGamesBrowse_C final : public UMCCMultiplayerCustomGamesBrowseScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0460(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Border;                                            // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* GameEngineHeader;                     // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* GameTypeHeader;                       // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Line;                                              // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     MainTitle;                                         // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* MapNameHeader;                        // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* PingHeader;                           // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* PlayersHeader;                        // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C* SessionHeader;                        // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowse(int32 EntryPoint);
	class FText Get_SearchInteractiveArea_AccessibleText_0();
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCMultiplayerCustomGamesBrowse_C">();
	}
	static class UWBP_MCCMultiplayerCustomGamesBrowse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCMultiplayerCustomGamesBrowse_C>();
	}
};
static_assert(alignof(UWBP_MCCMultiplayerCustomGamesBrowse_C) == 0x000008, "Wrong alignment on UWBP_MCCMultiplayerCustomGamesBrowse_C");
static_assert(sizeof(UWBP_MCCMultiplayerCustomGamesBrowse_C) == 0x0004B8, "Wrong size on UWBP_MCCMultiplayerCustomGamesBrowse_C");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, UberGraphFrame) == 0x000460, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, Border) == 0x000468, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::Border' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, GameEngineHeader) == 0x000470, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::GameEngineHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, GameTypeHeader) == 0x000478, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::GameTypeHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, Image_0) == 0x000480, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, Line) == 0x000488, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::Line' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, MainTitle) == 0x000490, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::MainTitle' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, MapNameHeader) == 0x000498, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::MapNameHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, PingHeader) == 0x0004A0, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::PingHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, PlayersHeader) == 0x0004A8, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::PlayersHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCMultiplayerCustomGamesBrowse_C, SessionHeader) == 0x0004B0, "Member 'UWBP_MCCMultiplayerCustomGamesBrowse_C::SessionHeader' has a wrong offset!");

}

