#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GammaStepper

#include "Basic.hpp"

#include "WBP_GammaStepper_classes.hpp"
#include "WBP_GammaStepper_parameters.hpp"


namespace SDK
{

// Function WBP_GammaStepper.WBP_GammaStepper_C.ExecuteUbergraph_WBP_GammaStepper
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GammaStepper_C::ExecuteUbergraph_WBP_GammaStepper(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GammaStepper_C", "ExecuteUbergraph_WBP_GammaStepper");

	Params::WBP_GammaStepper_C_ExecuteUbergraph_WBP_GammaStepper Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GammaStepper.WBP_GammaStepper_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_GammaStepper_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GammaStepper_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

