#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StoreDoubleItemBundle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C
// 0x0038 (0x03E0 - 0x03A8)
class UWBP_StoreDoubleItemBundle_C final : public UMCCStoreBundleWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       GlowAnimation;                                     // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Backing;                                           // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Backing_0;                                         // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 GoldFrame;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 GoldSpacer;                                        // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Spacer_0;                                          // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_StoreDoubleItemBundle(int32 EntryPoint);
	class FText Get_InteractiveWidget_AccessibleText_0();
	void NewFunction_0();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_StoreDoubleItemBundle_C">();
	}
	static class UWBP_StoreDoubleItemBundle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_StoreDoubleItemBundle_C>();
	}
};
static_assert(alignof(UWBP_StoreDoubleItemBundle_C) == 0x000008, "Wrong alignment on UWBP_StoreDoubleItemBundle_C");
static_assert(sizeof(UWBP_StoreDoubleItemBundle_C) == 0x0003E0, "Wrong size on UWBP_StoreDoubleItemBundle_C");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, UberGraphFrame) == 0x0003A8, "Member 'UWBP_StoreDoubleItemBundle_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, GlowAnimation) == 0x0003B0, "Member 'UWBP_StoreDoubleItemBundle_C::GlowAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, Backing) == 0x0003B8, "Member 'UWBP_StoreDoubleItemBundle_C::Backing' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, Backing_0) == 0x0003C0, "Member 'UWBP_StoreDoubleItemBundle_C::Backing_0' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, GoldFrame) == 0x0003C8, "Member 'UWBP_StoreDoubleItemBundle_C::GoldFrame' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, GoldSpacer) == 0x0003D0, "Member 'UWBP_StoreDoubleItemBundle_C::GoldSpacer' has a wrong offset!");
static_assert(offsetof(UWBP_StoreDoubleItemBundle_C, Spacer_0) == 0x0003D8, "Member 'UWBP_StoreDoubleItemBundle_C::Spacer_0' has a wrong offset!");

}

