#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCGameSessionDetails

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCGameSessionDetails.WBP_MCCGameSessionDetails_C
// 0x0028 (0x0378 - 0x0350)
class UWBP_MCCGameSessionDetails_C final : public UMCCGameSessionDetailsWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDConfigurableTextBlock*               GameSessionLeaderHeader;                           // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               MainHeader;                                        // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               PlayerCountHeader;                                 // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_0;                                     // 0x0370(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCGameSessionDetails(int32 EntryPoint);
	void OnContextChanged();
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCGameSessionDetails_C">();
	}
	static class UWBP_MCCGameSessionDetails_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCGameSessionDetails_C>();
	}
};
static_assert(alignof(UWBP_MCCGameSessionDetails_C) == 0x000008, "Wrong alignment on UWBP_MCCGameSessionDetails_C");
static_assert(sizeof(UWBP_MCCGameSessionDetails_C) == 0x000378, "Wrong size on UWBP_MCCGameSessionDetails_C");
static_assert(offsetof(UWBP_MCCGameSessionDetails_C, UberGraphFrame) == 0x000350, "Member 'UWBP_MCCGameSessionDetails_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCGameSessionDetails_C, GameSessionLeaderHeader) == 0x000358, "Member 'UWBP_MCCGameSessionDetails_C::GameSessionLeaderHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCGameSessionDetails_C, MainHeader) == 0x000360, "Member 'UWBP_MCCGameSessionDetails_C::MainHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCGameSessionDetails_C, PlayerCountHeader) == 0x000368, "Member 'UWBP_MCCGameSessionDetails_C::PlayerCountHeader' has a wrong offset!");
static_assert(offsetof(UWBP_MCCGameSessionDetails_C, VerticalBox_0) == 0x000370, "Member 'UWBP_MCCGameSessionDetails_C::VerticalBox_0' has a wrong offset!");

}

