#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatMessage

#include "Basic.hpp"

#include "WBP_TextChatMessage_classes.hpp"
#include "WBP_TextChatMessage_parameters.hpp"


namespace SDK
{

// Function WBP_TextChatMessage.WBP_TextChatMessage_C.ExecuteUbergraph_WBP_TextChatMessage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TextChatMessage_C::ExecuteUbergraph_WBP_TextChatMessage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "ExecuteUbergraph_WBP_TextChatMessage");

	Params::WBP_TextChatMessage_C_ExecuteUbergraph_WBP_TextChatMessage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.OnMenuButtonHighlightEnabled
// (Event, Protected, BlueprintEvent)

void UWBP_TextChatMessage_C::OnMenuButtonHighlightEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "OnMenuButtonHighlightEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.OnMenuButtonHighlightDisabled
// (Event, Protected, BlueprintEvent)

void UWBP_TextChatMessage_C::OnMenuButtonHighlightDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "OnMenuButtonHighlightDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.OnMessageLostFocus
// (Event, Protected, BlueprintEvent)

void UWBP_TextChatMessage_C::OnMessageLostFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "OnMessageLostFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.OnMessageGainedFocus
// (Event, Protected, BlueprintEvent)

void UWBP_TextChatMessage_C::OnMessageGainedFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "OnMessageGainedFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_TextChatMessage_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.SetMessageColors
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TextChatMessage_C::SetMessageColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "SetMessageColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.Get_FocusableArea_AccessibleText_0
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TextChatMessage_C::Get_FocusableArea_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "Get_FocusableArea_AccessibleText_0");

	Params::WBP_TextChatMessage_C_Get_FocusableArea_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TextChatMessage.WBP_TextChatMessage_C.Get_MenuButton_AccessibleText_0
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TextChatMessage_C::Get_MenuButton_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TextChatMessage_C", "Get_MenuButton_AccessibleText_0");

	Params::WBP_TextChatMessage_C_Get_MenuButton_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

