#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonTabs

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SeasonTabs.WBP_SeasonTabs_C
// 0x0048 (0x0418 - 0x03D0)
class UWBP_SeasonTabs_C final : public UMCCSeasonTabContainerWidget
{
public:
	class USDInputControllerWidgetSwitcher*       SDInputControllerWidgetSwitcher_0;                 // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDInputControllerWidgetSwitcher*       SDInputControllerWidgetSwitcher_1;                 // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTab_C*                       WBP_SeasonTab;                                     // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTab_C*                       WBP_SeasonTab_0;                                   // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTab_C*                       WBP_SeasonTab_1;                                   // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTab_C*                       WBP_SeasonTab_2;                                   // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTabLine_C*                   WBP_SeasonTabLine;                                 // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTabLine_C*                   WBP_SeasonTabLine_0;                               // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SeasonTabLine_C*                   WBP_SeasonTabLine_1;                               // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SeasonTabs_C">();
	}
	static class UWBP_SeasonTabs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SeasonTabs_C>();
	}
};
static_assert(alignof(UWBP_SeasonTabs_C) == 0x000008, "Wrong alignment on UWBP_SeasonTabs_C");
static_assert(sizeof(UWBP_SeasonTabs_C) == 0x000418, "Wrong size on UWBP_SeasonTabs_C");
static_assert(offsetof(UWBP_SeasonTabs_C, SDInputControllerWidgetSwitcher_0) == 0x0003D0, "Member 'UWBP_SeasonTabs_C::SDInputControllerWidgetSwitcher_0' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, SDInputControllerWidgetSwitcher_1) == 0x0003D8, "Member 'UWBP_SeasonTabs_C::SDInputControllerWidgetSwitcher_1' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTab) == 0x0003E0, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTab' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTab_0) == 0x0003E8, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTab_0' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTab_1) == 0x0003F0, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTab_1' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTab_2) == 0x0003F8, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTab_2' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTabLine) == 0x000400, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTabLine' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTabLine_0) == 0x000408, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTabLine_0' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabs_C, WBP_SeasonTabLine_1) == 0x000410, "Member 'UWBP_SeasonTabs_C::WBP_SeasonTabLine_1' has a wrong offset!");

}

