#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCPredefinedAnimations

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCPredefinedAnimations.WBP_MCCPredefinedAnimations_C
// 0x0038 (0x02A0 - 0x0268)
class UWBP_MCCPredefinedAnimations_C final : public UUserWidget
{
public:
	class UWidgetAnimation*                       Blink;                                             // 0x0268(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Colorize;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       MoveRight;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                BlinkExample;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Double1;                                           // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Double2;                                           // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                MoveRightWidget;                                   // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCPredefinedAnimations_C">();
	}
	static class UWBP_MCCPredefinedAnimations_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCPredefinedAnimations_C>();
	}
};
static_assert(alignof(UWBP_MCCPredefinedAnimations_C) == 0x000008, "Wrong alignment on UWBP_MCCPredefinedAnimations_C");
static_assert(sizeof(UWBP_MCCPredefinedAnimations_C) == 0x0002A0, "Wrong size on UWBP_MCCPredefinedAnimations_C");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, Blink) == 0x000268, "Member 'UWBP_MCCPredefinedAnimations_C::Blink' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, Colorize) == 0x000270, "Member 'UWBP_MCCPredefinedAnimations_C::Colorize' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, MoveRight) == 0x000278, "Member 'UWBP_MCCPredefinedAnimations_C::MoveRight' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, BlinkExample) == 0x000280, "Member 'UWBP_MCCPredefinedAnimations_C::BlinkExample' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, Double1) == 0x000288, "Member 'UWBP_MCCPredefinedAnimations_C::Double1' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, Double2) == 0x000290, "Member 'UWBP_MCCPredefinedAnimations_C::Double2' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPredefinedAnimations_C, MoveRightWidget) == 0x000298, "Member 'UWBP_MCCPredefinedAnimations_C::MoveRightWidget' has a wrong offset!");

}

