#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCBootmovie

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCBootmovie.WBP_MCCBootmovie_C
// 0x0010 (0x0378 - 0x0368)
class UWBP_MCCBootmovie_C final : public UMCCBootmovieWidget
{
public:
	class UImage*                                 Image_0;                                           // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              ScaleBox_37;                                       // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCBootmovie_C">();
	}
	static class UWBP_MCCBootmovie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCBootmovie_C>();
	}
};
static_assert(alignof(UWBP_MCCBootmovie_C) == 0x000008, "Wrong alignment on UWBP_MCCBootmovie_C");
static_assert(sizeof(UWBP_MCCBootmovie_C) == 0x000378, "Wrong size on UWBP_MCCBootmovie_C");
static_assert(offsetof(UWBP_MCCBootmovie_C, Image_0) == 0x000368, "Member 'UWBP_MCCBootmovie_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_MCCBootmovie_C, ScaleBox_37) == 0x000370, "Member 'UWBP_MCCBootmovie_C::ScaleBox_37' has a wrong offset!");

}

