#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCPlayerButtonPrompt

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SDCoreUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCPlayerButtonPrompt.WBP_MCCPlayerButtonPrompt_C
// 0x0028 (0x0350 - 0x0328)
class UWBP_MCCPlayerButtonPrompt_C final : public USDUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       MoveAnimation;                                     // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         InputPromptContainer;                              // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDInputControllerWidgetSwitcher*       InputSwitcher;                                     // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               Widget;                                            // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCPlayerButtonPrompt(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCPlayerButtonPrompt_C">();
	}
	static class UWBP_MCCPlayerButtonPrompt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCPlayerButtonPrompt_C>();
	}
};
static_assert(alignof(UWBP_MCCPlayerButtonPrompt_C) == 0x000008, "Wrong alignment on UWBP_MCCPlayerButtonPrompt_C");
static_assert(sizeof(UWBP_MCCPlayerButtonPrompt_C) == 0x000350, "Wrong size on UWBP_MCCPlayerButtonPrompt_C");
static_assert(offsetof(UWBP_MCCPlayerButtonPrompt_C, UberGraphFrame) == 0x000328, "Member 'UWBP_MCCPlayerButtonPrompt_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButtonPrompt_C, MoveAnimation) == 0x000330, "Member 'UWBP_MCCPlayerButtonPrompt_C::MoveAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButtonPrompt_C, InputPromptContainer) == 0x000338, "Member 'UWBP_MCCPlayerButtonPrompt_C::InputPromptContainer' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButtonPrompt_C, InputSwitcher) == 0x000340, "Member 'UWBP_MCCPlayerButtonPrompt_C::InputSwitcher' has a wrong offset!");
static_assert(offsetof(UWBP_MCCPlayerButtonPrompt_C, Widget) == 0x000348, "Member 'UWBP_MCCPlayerButtonPrompt_C::Widget' has a wrong offset!");

}

