#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCDialogBoxWide

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCDialogBoxWide.WBP_MCCDialogBoxWide_C
// 0x0068 (0x0550 - 0x04E8)
class UWBP_MCCDialogBoxWide_C final : public UMCCDialogBoxWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       MoveUp;                                            // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeIn;                                            // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackgroundDarkening;                               // 0x0500(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BottomModalBorder;                                 // 0x0508(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageGradientLeft;                                 // 0x0510(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageGradientRight;                                // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageLeft;                                         // 0x0520(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ModalBackground;                                   // 0x0528(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Subtitle;                                          // 0x0530(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TopModalBorder;                                    // 0x0538(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCDialogBoxButton_C*              WBP_MCCDialogBoxButton;                            // 0x0540(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MCCDialogBoxButton_C*              WBP_MCCDialogBoxButton_0;                          // 0x0548(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCDialogBoxWide(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void OnContextChanged();
	void OnEnterEvent();
	void OnExitEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCDialogBoxWide_C">();
	}
	static class UWBP_MCCDialogBoxWide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCDialogBoxWide_C>();
	}
};
static_assert(alignof(UWBP_MCCDialogBoxWide_C) == 0x000008, "Wrong alignment on UWBP_MCCDialogBoxWide_C");
static_assert(sizeof(UWBP_MCCDialogBoxWide_C) == 0x000550, "Wrong size on UWBP_MCCDialogBoxWide_C");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, UberGraphFrame) == 0x0004E8, "Member 'UWBP_MCCDialogBoxWide_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, MoveUp) == 0x0004F0, "Member 'UWBP_MCCDialogBoxWide_C::MoveUp' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, FadeIn) == 0x0004F8, "Member 'UWBP_MCCDialogBoxWide_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, BackgroundDarkening) == 0x000500, "Member 'UWBP_MCCDialogBoxWide_C::BackgroundDarkening' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, BottomModalBorder) == 0x000508, "Member 'UWBP_MCCDialogBoxWide_C::BottomModalBorder' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, ImageGradientLeft) == 0x000510, "Member 'UWBP_MCCDialogBoxWide_C::ImageGradientLeft' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, ImageGradientRight) == 0x000518, "Member 'UWBP_MCCDialogBoxWide_C::ImageGradientRight' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, ImageLeft) == 0x000520, "Member 'UWBP_MCCDialogBoxWide_C::ImageLeft' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, ModalBackground) == 0x000528, "Member 'UWBP_MCCDialogBoxWide_C::ModalBackground' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, Subtitle) == 0x000530, "Member 'UWBP_MCCDialogBoxWide_C::Subtitle' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, TopModalBorder) == 0x000538, "Member 'UWBP_MCCDialogBoxWide_C::TopModalBorder' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, WBP_MCCDialogBoxButton) == 0x000540, "Member 'UWBP_MCCDialogBoxWide_C::WBP_MCCDialogBoxButton' has a wrong offset!");
static_assert(offsetof(UWBP_MCCDialogBoxWide_C, WBP_MCCDialogBoxButton_0) == 0x000548, "Member 'UWBP_MCCDialogBoxWide_C::WBP_MCCDialogBoxButton_0' has a wrong offset!");

}

