#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Upsell

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Upsell.WBP_Upsell_C.ExecuteUbergraph_WBP_Upsell
// 0x0028 (0x0028 - 0x0000)
struct WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue1;          // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue1;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell) == 0x000008, "Wrong alignment on WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell");
static_assert(sizeof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell) == 0x000028, "Wrong size on WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, EntryPoint) == 0x000000, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000008, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, CallFunc_GetDynamicMaterial_ReturnValue1) == 0x000010, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::CallFunc_GetDynamicMaterial_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, CallFunc_GetOwningPlayer_ReturnValue) == 0x000018, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell, CallFunc_GetOwningPlayer_ReturnValue1) == 0x000020, "Member 'WBP_Upsell_C_ExecuteUbergraph_WBP_Upsell::CallFunc_GetOwningPlayer_ReturnValue1' has a wrong offset!");

// Function WBP_Upsell.WBP_Upsell_C.SetTextColor
// 0x0060 (0x0060 - 0x0000)
struct WBP_Upsell_C_SetTextColor final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAnyUserFocus_ReturnValue;              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FColor                                 CallFunc_Conv_LinearColorToColor_ReturnValue;      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_ColorToLinearColor_ReturnValue;      // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_GetColorByThemeName_ReturnValue;          // 0x0018(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0038(0x0028)()
};
static_assert(alignof(WBP_Upsell_C_SetTextColor) == 0x000008, "Wrong alignment on WBP_Upsell_C_SetTextColor");
static_assert(sizeof(WBP_Upsell_C_SetTextColor) == 0x000060, "Wrong size on WBP_Upsell_C_SetTextColor");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, Temp_bool_Variable) == 0x000000, "Member 'WBP_Upsell_C_SetTextColor::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, CallFunc_HasAnyUserFocus_ReturnValue) == 0x000001, "Member 'WBP_Upsell_C_SetTextColor::CallFunc_HasAnyUserFocus_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, CallFunc_Conv_LinearColorToColor_ReturnValue) == 0x000004, "Member 'WBP_Upsell_C_SetTextColor::CallFunc_Conv_LinearColorToColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, CallFunc_Conv_ColorToLinearColor_ReturnValue) == 0x000008, "Member 'WBP_Upsell_C_SetTextColor::CallFunc_Conv_ColorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, CallFunc_GetColorByThemeName_ReturnValue) == 0x000018, "Member 'WBP_Upsell_C_SetTextColor::CallFunc_GetColorByThemeName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, K2Node_Select_Default) == 0x000028, "Member 'WBP_Upsell_C_SetTextColor::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_Upsell_C_SetTextColor, K2Node_MakeStruct_SlateColor) == 0x000038, "Member 'WBP_Upsell_C_SetTextColor::K2Node_MakeStruct_SlateColor' has a wrong offset!");

}

