#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayFabItemReward

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayFabItemReward.WBP_PlayFabItemReward_C
// 0x0010 (0x0350 - 0x0340)
class UWBP_PlayFabItemReward_C final : public UMCCPlayFabRewardWidget
{
public:
	class UMCCUUIImage*                           FullHorizontalFrame;                               // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           ItemBGGradient;                                    // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PlayFabItemReward_C">();
	}
	static class UWBP_PlayFabItemReward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayFabItemReward_C>();
	}
};
static_assert(alignof(UWBP_PlayFabItemReward_C) == 0x000008, "Wrong alignment on UWBP_PlayFabItemReward_C");
static_assert(sizeof(UWBP_PlayFabItemReward_C) == 0x000350, "Wrong size on UWBP_PlayFabItemReward_C");
static_assert(offsetof(UWBP_PlayFabItemReward_C, FullHorizontalFrame) == 0x000340, "Member 'UWBP_PlayFabItemReward_C::FullHorizontalFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PlayFabItemReward_C, ItemBGGradient) == 0x000348, "Member 'UWBP_PlayFabItemReward_C::ItemBGGradient' has a wrong offset!");

}

