#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionSlider

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_OptionSlider.WBP_OptionSlider_C.ExecuteUbergraph_WBP_OptionSlider
// 0x04D8 (0x04D8 - 0x0000)
struct WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue1; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_MakeBrushFromMaterial_ReturnValue;        // 0x0018(0x0088)()
	struct FSlateBrush                            CallFunc_MakeBrushFromMaterial_ReturnValue1;       // 0x00A0(0x0088)()
	float                                         CallFunc_GetValue_ReturnValue;                     // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSliderStyle                           K2Node_MakeStruct_SliderStyle;                     // 0x0130(0x0340)()
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0470(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_UserIndex;              // 0x04AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x04B8(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x04D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider) == 0x000008, "Wrong alignment on WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider");
static_assert(sizeof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider) == 0x0004D8, "Wrong size on WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, EntryPoint) == 0x000000, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000008, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_CreateDynamicMaterialInstance_ReturnValue1) == 0x000010, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_CreateDynamicMaterialInstance_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_MakeBrushFromMaterial_ReturnValue) == 0x000018, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_MakeBrushFromMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_MakeBrushFromMaterial_ReturnValue1) == 0x0000A0, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_MakeBrushFromMaterial_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_GetValue_ReturnValue) == 0x000128, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_GetValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_MakeStruct_SliderStyle) == 0x000130, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_MakeStruct_SliderStyle' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_Event_MyGeometry) == 0x000470, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_Event_InDeltaTime) == 0x0004A8, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_ComponentBoundEvent_UserIndex) == 0x0004AC, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_ComponentBoundEvent_UserIndex' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, CallFunc_GetOwningPlayer_ReturnValue) == 0x0004B0, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_ComponentBoundEvent_Text) == 0x0004B8, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider, K2Node_ComponentBoundEvent_CommitMethod) == 0x0004D0, "Member 'WBP_OptionSlider_C_ExecuteUbergraph_WBP_OptionSlider::K2Node_ComponentBoundEvent_CommitMethod' has a wrong offset!");

// Function WBP_OptionSlider.WBP_OptionSlider_C.BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text_0;                                            // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature");
static_assert(sizeof(WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature) == 0x000020, "Wrong size on WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature");
static_assert(offsetof(WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature, Text_0) == 0x000000, "Member 'WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature::Text_0' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature, CommitMethod) == 0x000018, "Member 'WBP_OptionSlider_C_BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature::CommitMethod' has a wrong offset!");

// Function WBP_OptionSlider.WBP_OptionSlider_C.BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature final
{
public:
	int32                                         UserIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature");
static_assert(sizeof(WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature");
static_assert(offsetof(WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature, UserIndex) == 0x000000, "Member 'WBP_OptionSlider_C_BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature::UserIndex' has a wrong offset!");

// Function WBP_OptionSlider.WBP_OptionSlider_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_OptionSlider_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionSlider_C_Tick) == 0x000004, "Wrong alignment on WBP_OptionSlider_C_Tick");
static_assert(sizeof(WBP_OptionSlider_C_Tick) == 0x00003C, "Wrong size on WBP_OptionSlider_C_Tick");
static_assert(offsetof(WBP_OptionSlider_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_OptionSlider_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_OptionSlider_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_OptionSlider.WBP_OptionSlider_C.Get_Text_AccessibleText_0
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_OptionSlider_C_Get_Text_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_GetOptionName_ReturnValue;                // 0x0018(0x0018)(ConstParm)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0030(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue1;           // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue1;               // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0088(0x0018)()
};
static_assert(alignof(WBP_OptionSlider_C_Get_Text_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_OptionSlider_C_Get_Text_AccessibleText_0");
static_assert(sizeof(WBP_OptionSlider_C_Get_Text_AccessibleText_0) == 0x0000A0, "Wrong size on WBP_OptionSlider_C_Get_Text_AccessibleText_0");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_GetOptionName_ReturnValue) == 0x000018, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_GetOptionName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_GetText_ReturnValue) == 0x000030, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_Conv_TextToString_ReturnValue) == 0x000048, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_Conv_TextToString_ReturnValue1) == 0x000058, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_Conv_TextToString_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue) == 0x000068, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_Concat_StrStr_ReturnValue1) == 0x000078, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_Concat_StrStr_ReturnValue1' has a wrong offset!");
static_assert(offsetof(WBP_OptionSlider_C_Get_Text_AccessibleText_0, CallFunc_Conv_StringToText_ReturnValue) == 0x000088, "Member 'WBP_OptionSlider_C_Get_Text_AccessibleText_0::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");

}

