#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCFriendListItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCFriendListItem.WBP_MCCFriendListItem_C
// 0x0008 (0x0348 - 0x0340)
class UWBP_MCCFriendListItem_C final : public UMCCFriendListItemWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_MCCFriendListItem(int32 EntryPoint);
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCFriendListItem_C">();
	}
	static class UWBP_MCCFriendListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCFriendListItem_C>();
	}
};
static_assert(alignof(UWBP_MCCFriendListItem_C) == 0x000008, "Wrong alignment on UWBP_MCCFriendListItem_C");
static_assert(sizeof(UWBP_MCCFriendListItem_C) == 0x000348, "Wrong size on UWBP_MCCFriendListItem_C");
static_assert(offsetof(UWBP_MCCFriendListItem_C, UberGraphFrame) == 0x000340, "Member 'UWBP_MCCFriendListItem_C::UberGraphFrame' has a wrong offset!");

}

