#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationRoot

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_CustomizationRoot.WBP_CustomizationRoot_C.ExecuteUbergraph_WBP_CustomizationRoot
// 0x0078 (0x0078 - 0x0000)
struct WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0008(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable1;                      // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable1;                // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAssetLoaderVisible_ReturnValue;         // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47[0x1];                                       // 0x0047(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_GamePlayerCustomizationListWidget_C* K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_GamePlayerCustomizationListWidget_C* K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget1; // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_GamePlayerCustomizationListWidget_C* K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget2; // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot) == 0x000008, "Wrong alignment on WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot");
static_assert(sizeof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot) == 0x000078, "Wrong size on WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, EntryPoint) == 0x000000, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, Temp_bool_IsClosed_Variable) == 0x000004, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, Temp_bool_Has_Been_Initd_Variable) == 0x000005, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_Event_MyGeometry) == 0x000008, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_Event_InDeltaTime) == 0x000040, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, Temp_bool_IsClosed_Variable1) == 0x000044, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::Temp_bool_IsClosed_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, Temp_bool_Has_Been_Initd_Variable1) == 0x000045, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::Temp_bool_Has_Been_Initd_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, CallFunc_IsAssetLoaderVisible_ReturnValue) == 0x000046, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::CallFunc_IsAssetLoaderVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget) == 0x000048, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget1) == 0x000058, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_bSuccess1) == 0x000060, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_bSuccess1' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget2) == 0x000068, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_AsWBP_Game_Player_Customization_List_Widget2' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot, K2Node_DynamicCast_bSuccess2) == 0x000070, "Member 'WBP_CustomizationRoot_C_ExecuteUbergraph_WBP_CustomizationRoot::K2Node_DynamicCast_bSuccess2' has a wrong offset!");

// Function WBP_CustomizationRoot.WBP_CustomizationRoot_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_CustomizationRoot_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_CustomizationRoot_C_Tick) == 0x000004, "Wrong alignment on WBP_CustomizationRoot_C_Tick");
static_assert(sizeof(WBP_CustomizationRoot_C_Tick) == 0x00003C, "Wrong size on WBP_CustomizationRoot_C_Tick");
static_assert(offsetof(WBP_CustomizationRoot_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_CustomizationRoot_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_CustomizationRoot_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_CustomizationRoot_C_Tick::InDeltaTime' has a wrong offset!");

}

