#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GamePlayerListItem2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GamePlayerListItem2.WBP_GamePlayerListItem2_C
// 0x0060 (0x0420 - 0x03C0)
class UWBP_GamePlayerListItem2_C final : public UMCCCGamePlayerCustomizationListItemWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Stagger;                                           // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FlickerAnimation;                                  // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SelectAnimation;                                   // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       GlowAnimation;                                     // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ButtonImage;                                       // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               ButtonShadowText;                                  // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               ButtonSizeBox;                                     // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDTile*                                ButtonTile;                                        // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FocusedImage;                                      // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Name_0;                                            // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bIsSelected;                                       // 0x0418(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_GamePlayerListItem2(int32 EntryPoint);
	void BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnAreaClickedEvent__DelegateSignature();
	void PlayStaggerAnimation();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void OnContextChanged();
	void FocusReceived();
	void FocusLost();
	void SlotClicked();
	void Construct();
	class FText GetAccessibleText_0();
	void ToggleFocusedImageFocus(ESlateVisibility Visibility_0);
	void SetSelected(bool IsSelected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_GamePlayerListItem2_C">();
	}
	static class UWBP_GamePlayerListItem2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GamePlayerListItem2_C>();
	}
};
static_assert(alignof(UWBP_GamePlayerListItem2_C) == 0x000008, "Wrong alignment on UWBP_GamePlayerListItem2_C");
static_assert(sizeof(UWBP_GamePlayerListItem2_C) == 0x000420, "Wrong size on UWBP_GamePlayerListItem2_C");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, UberGraphFrame) == 0x0003C0, "Member 'UWBP_GamePlayerListItem2_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, Stagger) == 0x0003C8, "Member 'UWBP_GamePlayerListItem2_C::Stagger' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, FlickerAnimation) == 0x0003D0, "Member 'UWBP_GamePlayerListItem2_C::FlickerAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, SelectAnimation) == 0x0003D8, "Member 'UWBP_GamePlayerListItem2_C::SelectAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, GlowAnimation) == 0x0003E0, "Member 'UWBP_GamePlayerListItem2_C::GlowAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, ButtonImage) == 0x0003E8, "Member 'UWBP_GamePlayerListItem2_C::ButtonImage' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, ButtonShadowText) == 0x0003F0, "Member 'UWBP_GamePlayerListItem2_C::ButtonShadowText' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, ButtonSizeBox) == 0x0003F8, "Member 'UWBP_GamePlayerListItem2_C::ButtonSizeBox' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, ButtonTile) == 0x000400, "Member 'UWBP_GamePlayerListItem2_C::ButtonTile' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, FocusedImage) == 0x000408, "Member 'UWBP_GamePlayerListItem2_C::FocusedImage' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, Name_0) == 0x000410, "Member 'UWBP_GamePlayerListItem2_C::Name_0' has a wrong offset!");
static_assert(offsetof(UWBP_GamePlayerListItem2_C, bIsSelected) == 0x000418, "Member 'UWBP_GamePlayerListItem2_C::bIsSelected' has a wrong offset!");

}

