#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BackgroundCustomizationGridItem

#include "Basic.hpp"

#include "WBP_BackgroundCustomizationGridItem_classes.hpp"
#include "WBP_BackgroundCustomizationGridItem_parameters.hpp"


namespace SDK
{

// Function WBP_BackgroundCustomizationGridItem.WBP_BackgroundCustomizationGridItem_C.ExecuteUbergraph_WBP_BackgroundCustomizationGridItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BackgroundCustomizationGridItem_C::ExecuteUbergraph_WBP_BackgroundCustomizationGridItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BackgroundCustomizationGridItem_C", "ExecuteUbergraph_WBP_BackgroundCustomizationGridItem");

	Params::WBP_BackgroundCustomizationGridItem_C_ExecuteUbergraph_WBP_BackgroundCustomizationGridItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BackgroundCustomizationGridItem.WBP_BackgroundCustomizationGridItem_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_BackgroundCustomizationGridItem_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BackgroundCustomizationGridItem_C", "OnAddedToFocusPath");

	Params::WBP_BackgroundCustomizationGridItem_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BackgroundCustomizationGridItem.WBP_BackgroundCustomizationGridItem_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_BackgroundCustomizationGridItem_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BackgroundCustomizationGridItem_C", "OnRemovedFromFocusPath");

	Params::WBP_BackgroundCustomizationGridItem_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}

}

