#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionEditableText

#include "Basic.hpp"

#include "WBP_OptionEditableText_classes.hpp"
#include "WBP_OptionEditableText_parameters.hpp"


namespace SDK
{

// Function WBP_OptionEditableText.WBP_OptionEditableText_C.ExecuteUbergraph_WBP_OptionEditableText
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionEditableText_C::ExecuteUbergraph_WBP_OptionEditableText(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionEditableText_C", "ExecuteUbergraph_WBP_OptionEditableText");

	Params::WBP_OptionEditableText_C_ExecuteUbergraph_WBP_OptionEditableText Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionEditableText.WBP_OptionEditableText_C.Get_InteractiveArea_AccessibleText_0
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_OptionEditableText_C::Get_InteractiveArea_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionEditableText_C", "Get_InteractiveArea_AccessibleText_0");

	Params::WBP_OptionEditableText_C_Get_InteractiveArea_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_OptionEditableText.WBP_OptionEditableText_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_OptionEditableText_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionEditableText_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

