#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionSlider

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_OptionSlider.WBP_OptionSlider_C
// 0x0030 (0x0500 - 0x04D0)
class UWBP_OptionSlider_C final : public UMCCOptionSliderWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TextChange;                                        // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDButton*                              PrimaryBinding;                                    // 0x04E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MaterialDynamicBlue;                               // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MaterialDynamicWhite;                              // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_OptionSlider(int32 EntryPoint);
	void BndEvt__SDEditableTextBox_0_K2Node_ComponentBoundEvent_0_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text_0, ETextCommit CommitMethod);
	void BndEvt__PrimaryBinding_K2Node_ComponentBoundEvent_3_OnWidgetClickedEvent__DelegateSignature(int32 UserIndex);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	class FText Get_Text_AccessibleText_0();
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_OptionSlider_C">();
	}
	static class UWBP_OptionSlider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OptionSlider_C>();
	}
};
static_assert(alignof(UWBP_OptionSlider_C) == 0x000008, "Wrong alignment on UWBP_OptionSlider_C");
static_assert(sizeof(UWBP_OptionSlider_C) == 0x000500, "Wrong size on UWBP_OptionSlider_C");
static_assert(offsetof(UWBP_OptionSlider_C, UberGraphFrame) == 0x0004D0, "Member 'UWBP_OptionSlider_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSlider_C, TextChange) == 0x0004D8, "Member 'UWBP_OptionSlider_C::TextChange' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSlider_C, Image_0) == 0x0004E0, "Member 'UWBP_OptionSlider_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSlider_C, PrimaryBinding) == 0x0004E8, "Member 'UWBP_OptionSlider_C::PrimaryBinding' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSlider_C, MaterialDynamicBlue) == 0x0004F0, "Member 'UWBP_OptionSlider_C::MaterialDynamicBlue' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSlider_C, MaterialDynamicWhite) == 0x0004F8, "Member 'UWBP_OptionSlider_C::MaterialDynamicWhite' has a wrong offset!");

}

