#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationCategoryColorSelectorGridSlot

#include "Basic.hpp"

#include "WBP_CustomizationCategoryColorSelectorGridSlot_classes.hpp"
#include "WBP_CustomizationCategoryColorSelectorGridSlot_parameters.hpp"


namespace SDK
{

// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.ExecuteUbergraph_WBP_CustomizationCategoryColorSelectorGridSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::ExecuteUbergraph_WBP_CustomizationCategoryColorSelectorGridSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "ExecuteUbergraph_WBP_CustomizationCategoryColorSelectorGridSlot");

	Params::WBP_CustomizationCategoryColorSelectorGridSlot_C_ExecuteUbergraph_WBP_CustomizationCategoryColorSelectorGridSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.LockStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ELockState                              LockState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::LockStateChanged(ELockState LockState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "LockStateChanged");

	Params::WBP_CustomizationCategoryColorSelectorGridSlot_C_LockStateChanged Parms{};

	Parms.LockState = LockState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.SlotClicked
// (BlueprintCallable, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::SlotClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "SlotClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.FocusLost
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::FocusLost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "FocusLost");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.FocusReceived
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::FocusReceived()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "FocusReceived");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryColorSelectorGridSlot.WBP_CustomizationCategoryColorSelectorGridSlot_C.SetSelected
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Is_Selected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CustomizationCategoryColorSelectorGridSlot_C::SetSelected(bool Is_Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryColorSelectorGridSlot_C", "SetSelected");

	Params::WBP_CustomizationCategoryColorSelectorGridSlot_C_SetSelected Parms{};

	Parms.Is_Selected = Is_Selected;

	UObject::ProcessEvent(Func, &Parms);
}

}

