#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StoreDoubleItemBundle

#include "Basic.hpp"

#include "WBP_StoreDoubleItemBundle_classes.hpp"
#include "WBP_StoreDoubleItemBundle_parameters.hpp"


namespace SDK
{

// Function WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C.ExecuteUbergraph_WBP_StoreDoubleItemBundle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StoreDoubleItemBundle_C::ExecuteUbergraph_WBP_StoreDoubleItemBundle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StoreDoubleItemBundle_C", "ExecuteUbergraph_WBP_StoreDoubleItemBundle");

	Params::WBP_StoreDoubleItemBundle_C_ExecuteUbergraph_WBP_StoreDoubleItemBundle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C.Get_InteractiveWidget_AccessibleText_0
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_StoreDoubleItemBundle_C::Get_InteractiveWidget_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StoreDoubleItemBundle_C", "Get_InteractiveWidget_AccessibleText_0");

	Params::WBP_StoreDoubleItemBundle_C_Get_InteractiveWidget_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C.NewFunction_0
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_StoreDoubleItemBundle_C::NewFunction_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StoreDoubleItemBundle_C", "NewFunction_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_StoreDoubleItemBundle_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StoreDoubleItemBundle_C", "OnAddedToFocusPath");

	Params::WBP_StoreDoubleItemBundle_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StoreDoubleItemBundle.WBP_StoreDoubleItemBundle_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_StoreDoubleItemBundle_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StoreDoubleItemBundle_C", "OnRemovedFromFocusPath");

	Params::WBP_StoreDoubleItemBundle_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}

}

