#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerDetailsScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayerDetailsScreen.WBP_PlayerDetailsScreen_C
// 0x0058 (0x0448 - 0x03F0)
class UWBP_PlayerDetailsScreen_C final : public UMCCPlayerDetailsWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 BackgroundDarkening;                               // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LevelIcon;                                         // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MultiplayerRankBacking;                            // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 NextRewardDecoratorBottom;                         // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 NextRewardDecoratorTop;                            // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RewardIcon;                                        // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RivalBorder;                                       // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ServiceTagBg;                                      // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ServiceTagBgBorder;                                // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               Progressaterial;                                   // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PlayerDetailsScreen(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PlayerDetailsScreen_C">();
	}
	static class UWBP_PlayerDetailsScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerDetailsScreen_C>();
	}
};
static_assert(alignof(UWBP_PlayerDetailsScreen_C) == 0x000008, "Wrong alignment on UWBP_PlayerDetailsScreen_C");
static_assert(sizeof(UWBP_PlayerDetailsScreen_C) == 0x000448, "Wrong size on UWBP_PlayerDetailsScreen_C");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, UberGraphFrame) == 0x0003F0, "Member 'UWBP_PlayerDetailsScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, BackgroundDarkening) == 0x0003F8, "Member 'UWBP_PlayerDetailsScreen_C::BackgroundDarkening' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, LevelIcon) == 0x000400, "Member 'UWBP_PlayerDetailsScreen_C::LevelIcon' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, MultiplayerRankBacking) == 0x000408, "Member 'UWBP_PlayerDetailsScreen_C::MultiplayerRankBacking' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, NextRewardDecoratorBottom) == 0x000410, "Member 'UWBP_PlayerDetailsScreen_C::NextRewardDecoratorBottom' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, NextRewardDecoratorTop) == 0x000418, "Member 'UWBP_PlayerDetailsScreen_C::NextRewardDecoratorTop' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, RewardIcon) == 0x000420, "Member 'UWBP_PlayerDetailsScreen_C::RewardIcon' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, RivalBorder) == 0x000428, "Member 'UWBP_PlayerDetailsScreen_C::RivalBorder' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, ServiceTagBg) == 0x000430, "Member 'UWBP_PlayerDetailsScreen_C::ServiceTagBg' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, ServiceTagBgBorder) == 0x000438, "Member 'UWBP_PlayerDetailsScreen_C::ServiceTagBgBorder' has a wrong offset!");
static_assert(offsetof(UWBP_PlayerDetailsScreen_C, Progressaterial) == 0x000440, "Member 'UWBP_PlayerDetailsScreen_C::Progressaterial' has a wrong offset!");

}

