#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationVoicePreviewGridSlot

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CustomizationVoicePreviewGridSlot.WBP_CustomizationVoicePreviewGridSlot_C.ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot
// 0x0004 (0x0004 - 0x0000)
struct WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot) == 0x000004, "Wrong alignment on WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot");
static_assert(sizeof(WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot) == 0x000004, "Wrong size on WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot");
static_assert(offsetof(WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot, EntryPoint) == 0x000000, "Member 'WBP_CustomizationVoicePreviewGridSlot_C_ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot::EntryPoint' has a wrong offset!");

}

