#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCCloseBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCCloseBox.WBP_MCCCloseBox_C
// 0x0020 (0x0360 - 0x0340)
class UWBP_MCCCloseBox_C final : public UMCCCloseBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDTile*                                CloseBox;                                          // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CloseButton;                                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDInputControllerWidgetSwitcher*       SDInputControllerWidgetSwitcher_0;                 // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCCloseBox(int32 EntryPoint);
	void BndEvt__CloseBox_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature(int32 UserIndex);
	void BndEvt__SDTile_2_K2Node_ComponentBoundEvent_5_OnWidgetHoverEvent__DelegateSignature();
	void BndEvt__SDTile_2_K2Node_ComponentBoundEvent_6_OnWidgetHoverEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCCloseBox_C">();
	}
	static class UWBP_MCCCloseBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCCloseBox_C>();
	}
};
static_assert(alignof(UWBP_MCCCloseBox_C) == 0x000008, "Wrong alignment on UWBP_MCCCloseBox_C");
static_assert(sizeof(UWBP_MCCCloseBox_C) == 0x000360, "Wrong size on UWBP_MCCCloseBox_C");
static_assert(offsetof(UWBP_MCCCloseBox_C, UberGraphFrame) == 0x000340, "Member 'UWBP_MCCCloseBox_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCCloseBox_C, CloseBox) == 0x000348, "Member 'UWBP_MCCCloseBox_C::CloseBox' has a wrong offset!");
static_assert(offsetof(UWBP_MCCCloseBox_C, CloseButton) == 0x000350, "Member 'UWBP_MCCCloseBox_C::CloseButton' has a wrong offset!");
static_assert(offsetof(UWBP_MCCCloseBox_C, SDInputControllerWidgetSwitcher_0) == 0x000358, "Member 'UWBP_MCCCloseBox_C::SDInputControllerWidgetSwitcher_0' has a wrong offset!");

}

