#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonTabLine

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SeasonTabLine.WBP_SeasonTabLine_C
// 0x0020 (0x0350 - 0x0330)
class UWBP_SeasonTabLine_C final : public UMCCSeasonLineWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       LineUnlockedPulse;                                 // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        PageStatus;                                        // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        NewVar_0;                                          // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_SeasonTabLine(int32 EntryPoint);
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SeasonTabLine_C">();
	}
	static class UWBP_SeasonTabLine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SeasonTabLine_C>();
	}
};
static_assert(alignof(UWBP_SeasonTabLine_C) == 0x000008, "Wrong alignment on UWBP_SeasonTabLine_C");
static_assert(sizeof(UWBP_SeasonTabLine_C) == 0x000350, "Wrong size on UWBP_SeasonTabLine_C");
static_assert(offsetof(UWBP_SeasonTabLine_C, UberGraphFrame) == 0x000330, "Member 'UWBP_SeasonTabLine_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabLine_C, LineUnlockedPulse) == 0x000338, "Member 'UWBP_SeasonTabLine_C::LineUnlockedPulse' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabLine_C, PageStatus) == 0x000340, "Member 'UWBP_SeasonTabLine_C::PageStatus' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTabLine_C, NewVar_0) == 0x000348, "Member 'UWBP_SeasonTabLine_C::NewVar_0' has a wrong offset!");

}

