#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HorizontalWidgetArray

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_HorizontalWidgetArray.WBP_HorizontalWidgetArray_C.ExecuteUbergraph_WBP_HorizontalWidgetArray
// 0x0004 (0x0004 - 0x0000)
struct WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray) == 0x000004, "Wrong alignment on WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray");
static_assert(sizeof(WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray) == 0x000004, "Wrong size on WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray");
static_assert(offsetof(WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray, EntryPoint) == 0x000000, "Member 'WBP_HorizontalWidgetArray_C_ExecuteUbergraph_WBP_HorizontalWidgetArray::EntryPoint' has a wrong offset!");

}

