#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionDropdown

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_OptionDropdown.WBP_OptionDropdown_C.ExecuteUbergraph_WBP_OptionDropdown
// 0x0048 (0x0048 - 0x0000)
struct WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown) == 0x000008, "Wrong alignment on WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown");
static_assert(sizeof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown) == 0x000048, "Wrong size on WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, EntryPoint) == 0x000000, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, Temp_int_Array_Index_Variable) == 0x000010, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_Array_Get_Item) == 0x000018, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_Conv_NameToString_ReturnValue) == 0x000028, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, Temp_int_Loop_Counter_Variable) == 0x000038, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_OptionDropdown.WBP_OptionDropdown_C.On_ComboBox_GenerateWidget
// 0x0040 (0x0040 - 0x0000)
struct WBP_OptionDropdown_C_On_ComboBox_GenerateWidget final
{
public:
	class FString                                 item;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UWidget*                                ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0020(0x0018)()
	class UWBP_OptionDropdownButton_C*            CallFunc_Create_ReturnValue;                       // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget) == 0x000008, "Wrong alignment on WBP_OptionDropdown_C_On_ComboBox_GenerateWidget");
static_assert(sizeof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget) == 0x000040, "Wrong size on WBP_OptionDropdown_C_On_ComboBox_GenerateWidget");
static_assert(offsetof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget, item) == 0x000000, "Member 'WBP_OptionDropdown_C_On_ComboBox_GenerateWidget::item' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget, ReturnValue) == 0x000010, "Member 'WBP_OptionDropdown_C_On_ComboBox_GenerateWidget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget, CallFunc_GetOwningPlayer_ReturnValue) == 0x000018, "Member 'WBP_OptionDropdown_C_On_ComboBox_GenerateWidget::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget, CallFunc_Conv_StringToText_ReturnValue) == 0x000020, "Member 'WBP_OptionDropdown_C_On_ComboBox_GenerateWidget::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_On_ComboBox_GenerateWidget, CallFunc_Create_ReturnValue) == 0x000038, "Member 'WBP_OptionDropdown_C_On_ComboBox_GenerateWidget::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function WBP_OptionDropdown.WBP_OptionDropdown_C.OnFocusReceived
// 0x01B0 (0x01B0 - 0x0000)
struct WBP_OptionDropdown_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_OnFocusReceived_ReturnValue;              // 0x00F8(0x00B8)()
};
static_assert(alignof(WBP_OptionDropdown_C_OnFocusReceived) == 0x000008, "Wrong alignment on WBP_OptionDropdown_C_OnFocusReceived");
static_assert(sizeof(WBP_OptionDropdown_C_OnFocusReceived) == 0x0001B0, "Wrong size on WBP_OptionDropdown_C_OnFocusReceived");
static_assert(offsetof(WBP_OptionDropdown_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'WBP_OptionDropdown_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_OnFocusReceived, InFocusEvent) == 0x000038, "Member 'WBP_OptionDropdown_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_OnFocusReceived, ReturnValue) == 0x000040, "Member 'WBP_OptionDropdown_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OptionDropdown_C_OnFocusReceived, CallFunc_OnFocusReceived_ReturnValue) == 0x0000F8, "Member 'WBP_OptionDropdown_C_OnFocusReceived::CallFunc_OnFocusReceived_ReturnValue' has a wrong offset!");

}

