#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationVoicePreviewGridSlot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CustomizationVoicePreviewGridSlot.WBP_CustomizationVoicePreviewGridSlot_C
// 0x0038 (0x03D8 - 0x03A0)
class UWBP_CustomizationVoicePreviewGridSlot_C final : public UMCCCustomizationCategoryGridSlotPreviewWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       SelectAnimation;                                   // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       PreviewButtonGlow;                                 // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       PreviewButtonClick;                                // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconLocked;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconUnlockedDeselected;                            // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconUnlockedSelected;                              // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CustomizationVoicePreviewGridSlot(int32 EntryPoint);
	void PreviewButtonClicked();
	void PreviewButtonHovered();
	void PreviewButtonUnhovered();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CustomizationVoicePreviewGridSlot_C">();
	}
	static class UWBP_CustomizationVoicePreviewGridSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomizationVoicePreviewGridSlot_C>();
	}
};
static_assert(alignof(UWBP_CustomizationVoicePreviewGridSlot_C) == 0x000008, "Wrong alignment on UWBP_CustomizationVoicePreviewGridSlot_C");
static_assert(sizeof(UWBP_CustomizationVoicePreviewGridSlot_C) == 0x0003D8, "Wrong size on UWBP_CustomizationVoicePreviewGridSlot_C");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, UberGraphFrame) == 0x0003A0, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, SelectAnimation) == 0x0003A8, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::SelectAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, PreviewButtonGlow) == 0x0003B0, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::PreviewButtonGlow' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, PreviewButtonClick) == 0x0003B8, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::PreviewButtonClick' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, IconLocked) == 0x0003C0, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::IconLocked' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, IconUnlockedDeselected) == 0x0003C8, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::IconUnlockedDeselected' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationVoicePreviewGridSlot_C, IconUnlockedSelected) == 0x0003D0, "Member 'UWBP_CustomizationVoicePreviewGridSlot_C::IconUnlockedSelected' has a wrong offset!");

}

