#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionInputControllerBinding

#include "Basic.hpp"

#include "WBP_OptionInputControllerBinding_classes.hpp"
#include "WBP_OptionInputControllerBinding_parameters.hpp"


namespace SDK
{

// Function WBP_OptionInputControllerBinding.WBP_OptionInputControllerBinding_C.ExecuteUbergraph_WBP_OptionInputControllerBinding
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionInputControllerBinding_C::ExecuteUbergraph_WBP_OptionInputControllerBinding(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionInputControllerBinding_C", "ExecuteUbergraph_WBP_OptionInputControllerBinding");

	Params::WBP_OptionInputControllerBinding_C_ExecuteUbergraph_WBP_OptionInputControllerBinding Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionInputControllerBinding.WBP_OptionInputControllerBinding_C.Get_PrimaryBinding_AccessibleText_0
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_OptionInputControllerBinding_C::Get_PrimaryBinding_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionInputControllerBinding_C", "Get_PrimaryBinding_AccessibleText_0");

	Params::WBP_OptionInputControllerBinding_C_Get_PrimaryBinding_AccessibleText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_OptionInputControllerBinding.WBP_OptionInputControllerBinding_C.Get_Primarybinding_TextAsControllerIcon
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_OptionInputControllerBinding_C::Get_Primarybinding_TextAsControllerIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionInputControllerBinding_C", "Get_Primarybinding_TextAsControllerIcon");

	Params::WBP_OptionInputControllerBinding_C_Get_Primarybinding_TextAsControllerIcon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_OptionInputControllerBinding.WBP_OptionInputControllerBinding_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_OptionInputControllerBinding_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionInputControllerBinding_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

