#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMultiplayerCustomGamesSessionDetails

#include "Basic.hpp"

#include "WBP_MCCMultiplayerCustomGamesSessionDetails_classes.hpp"
#include "WBP_MCCMultiplayerCustomGamesSessionDetails_parameters.hpp"


namespace SDK
{

// Function WBP_MCCMultiplayerCustomGamesSessionDetails.WBP_MCCMultiplayerCustomGamesSessionDetails_C.ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesSessionDetails
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCMultiplayerCustomGamesSessionDetails_C::ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesSessionDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesSessionDetails_C", "ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesSessionDetails");

	Params::WBP_MCCMultiplayerCustomGamesSessionDetails_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesSessionDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCMultiplayerCustomGamesSessionDetails.WBP_MCCMultiplayerCustomGamesSessionDetails_C.UpdateGamertag
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_MCCMultiplayerCustomGamesSessionDetails_C::UpdateGamertag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesSessionDetails_C", "UpdateGamertag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MCCMultiplayerCustomGamesSessionDetails.WBP_MCCMultiplayerCustomGamesSessionDetails_C.UpdateVisuals
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsDifficultyHidden                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsTeamsHidden                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MCCMultiplayerCustomGamesSessionDetails_C::UpdateVisuals(bool bIsDifficultyHidden, bool bIsTeamsHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesSessionDetails_C", "UpdateVisuals");

	Params::WBP_MCCMultiplayerCustomGamesSessionDetails_C_UpdateVisuals Parms{};

	Parms.bIsDifficultyHidden = bIsDifficultyHidden;
	Parms.bIsTeamsHidden = bIsTeamsHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCMultiplayerCustomGamesSessionDetails.WBP_MCCMultiplayerCustomGamesSessionDetails_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_MCCMultiplayerCustomGamesSessionDetails_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMultiplayerCustomGamesSessionDetails_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

