#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationCategoryFoldoutGridSlot

#include "Basic.hpp"

#include "WBP_CustomizationCategoryFoldoutGridSlot_classes.hpp"
#include "WBP_CustomizationCategoryFoldoutGridSlot_parameters.hpp"


namespace SDK
{

// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.ExecuteUbergraph_WBP_CustomizationCategoryFoldoutGridSlot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::ExecuteUbergraph_WBP_CustomizationCategoryFoldoutGridSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "ExecuteUbergraph_WBP_CustomizationCategoryFoldoutGridSlot");

	Params::WBP_CustomizationCategoryFoldoutGridSlot_C_ExecuteUbergraph_WBP_CustomizationCategoryFoldoutGridSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.OnUnfold
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bFoldoutState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::OnUnfold(bool bFoldoutState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "OnUnfold");

	Params::WBP_CustomizationCategoryFoldoutGridSlot_C_OnUnfold Parms{};

	Parms.bFoldoutState = bFoldoutState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.FocusLost
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::FocusLost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "FocusLost");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.FocusReceived
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::FocusReceived()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "FocusReceived");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CustomizationCategoryFoldoutGridSlot.WBP_CustomizationCategoryFoldoutGridSlot_C.SetSelected
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CustomizationCategoryFoldoutGridSlot_C::SetSelected(bool bIsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationCategoryFoldoutGridSlot_C", "SetSelected");

	Params::WBP_CustomizationCategoryFoldoutGridSlot_C_SetSelected Parms{};

	Parms.bIsSelected_0 = bIsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

