#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionDropdown

#include "Basic.hpp"

#include "WBP_OptionDropdown_classes.hpp"
#include "WBP_OptionDropdown_parameters.hpp"


namespace SDK
{

// Function WBP_OptionDropdown.WBP_OptionDropdown_C.ExecuteUbergraph_WBP_OptionDropdown
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionDropdown_C::ExecuteUbergraph_WBP_OptionDropdown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "ExecuteUbergraph_WBP_OptionDropdown");

	Params::WBP_OptionDropdown_C_ExecuteUbergraph_WBP_OptionDropdown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionDropdown.WBP_OptionDropdown_C.Focused
// (BlueprintCallable, BlueprintEvent)

void UWBP_OptionDropdown_C::Focused()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "Focused");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionDropdown.WBP_OptionDropdown_C.Get_ComboBox_AccessibleText_0
// (Protected, BlueprintCallable, BlueprintEvent, BlueprintPure)

void UWBP_OptionDropdown_C::Get_ComboBox_AccessibleText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "Get_ComboBox_AccessibleText_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionDropdown.WBP_OptionDropdown_C.On_ComboBox_GenerateWidget
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_OptionDropdown_C::On_ComboBox_GenerateWidget(const class FString& item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "On_ComboBox_GenerateWidget");

	Params::WBP_OptionDropdown_C_On_ComboBox_GenerateWidget Parms{};

	Parms.item = std::move(item);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_OptionDropdown.WBP_OptionDropdown_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_OptionDropdown_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionDropdown.WBP_OptionDropdown_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_OptionDropdown_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionDropdown_C", "OnFocusReceived");

	Params::WBP_OptionDropdown_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

