#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatMessage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TextChatMessage.WBP_TextChatMessage_C
// 0x0058 (0x03F8 - 0x03A0)
class UWBP_TextChatMessage_C final : public UMCCTextChatMessageWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             Channel;                                           // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           ChannelContainer;                                  // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               CVAA;                                              // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FocusHightlight;                                   // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MenuBackground;                                    // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Message;                                           // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         NameContainer;                                     // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Timestamp;                                         // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             UserName;                                          // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             VoiceChannel;                                      // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_TextChatMessage(int32 EntryPoint);
	void OnMenuButtonHighlightEnabled();
	void OnMenuButtonHighlightDisabled();
	void OnMessageLostFocus();
	void OnMessageGainedFocus();
	void OnContextChanged();
	void SetMessageColors();
	class FText Get_FocusableArea_AccessibleText_0();
	class FText Get_MenuButton_AccessibleText_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TextChatMessage_C">();
	}
	static class UWBP_TextChatMessage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TextChatMessage_C>();
	}
};
static_assert(alignof(UWBP_TextChatMessage_C) == 0x000008, "Wrong alignment on UWBP_TextChatMessage_C");
static_assert(sizeof(UWBP_TextChatMessage_C) == 0x0003F8, "Wrong size on UWBP_TextChatMessage_C");
static_assert(offsetof(UWBP_TextChatMessage_C, UberGraphFrame) == 0x0003A0, "Member 'UWBP_TextChatMessage_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, Channel) == 0x0003A8, "Member 'UWBP_TextChatMessage_C::Channel' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, ChannelContainer) == 0x0003B0, "Member 'UWBP_TextChatMessage_C::ChannelContainer' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, CVAA) == 0x0003B8, "Member 'UWBP_TextChatMessage_C::CVAA' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, FocusHightlight) == 0x0003C0, "Member 'UWBP_TextChatMessage_C::FocusHightlight' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, MenuBackground) == 0x0003C8, "Member 'UWBP_TextChatMessage_C::MenuBackground' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, Message) == 0x0003D0, "Member 'UWBP_TextChatMessage_C::Message' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, NameContainer) == 0x0003D8, "Member 'UWBP_TextChatMessage_C::NameContainer' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, Timestamp) == 0x0003E0, "Member 'UWBP_TextChatMessage_C::Timestamp' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, UserName) == 0x0003E8, "Member 'UWBP_TextChatMessage_C::UserName' has a wrong offset!");
static_assert(offsetof(UWBP_TextChatMessage_C, VoiceChannel) == 0x0003F0, "Member 'UWBP_TextChatMessage_C::VoiceChannel' has a wrong offset!");

}

