#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Watermark

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Watermark.WBP_Watermark_C
// 0x0010 (0x0368 - 0x0358)
class UWBP_Watermark_C final : public UMCCWatermarkWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USDConfigurableTextBlock*               WatermarkText;                                     // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Watermark(int32 EntryPoint);
	void OnContextChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Watermark_C">();
	}
	static class UWBP_Watermark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Watermark_C>();
	}
};
static_assert(alignof(UWBP_Watermark_C) == 0x000008, "Wrong alignment on UWBP_Watermark_C");
static_assert(sizeof(UWBP_Watermark_C) == 0x000368, "Wrong size on UWBP_Watermark_C");
static_assert(offsetof(UWBP_Watermark_C, UberGraphFrame) == 0x000358, "Member 'UWBP_Watermark_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Watermark_C, WatermarkText) == 0x000360, "Member 'UWBP_Watermark_C::WatermarkText' has a wrong offset!");

}

