#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SeasonTab.WBP_SeasonTab_C
// 0x0020 (0x0598 - 0x0578)
class UWBP_SeasonTab_C final : public UMCCSeasonTabWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0578(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TabSelectedPulse;                                  // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CurrentTab;                                        // 0x0588(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        TierStatus;                                        // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_SeasonTab(int32 EntryPoint);
	void UpdateSelection(const bool IsSelected);
	void OnContextChanged();
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void UpdateSelectedVisuals(bool bIsSelected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SeasonTab_C">();
	}
	static class UWBP_SeasonTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SeasonTab_C>();
	}
};
static_assert(alignof(UWBP_SeasonTab_C) == 0x000008, "Wrong alignment on UWBP_SeasonTab_C");
static_assert(sizeof(UWBP_SeasonTab_C) == 0x000598, "Wrong size on UWBP_SeasonTab_C");
static_assert(offsetof(UWBP_SeasonTab_C, UberGraphFrame) == 0x000578, "Member 'UWBP_SeasonTab_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTab_C, TabSelectedPulse) == 0x000580, "Member 'UWBP_SeasonTab_C::TabSelectedPulse' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTab_C, CurrentTab) == 0x000588, "Member 'UWBP_SeasonTab_C::CurrentTab' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonTab_C, TierStatus) == 0x000590, "Member 'UWBP_SeasonTab_C::TierStatus' has a wrong offset!");

}

