#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerDetailsScreen

#include "Basic.hpp"

#include "WBP_PlayerDetailsScreen_classes.hpp"
#include "WBP_PlayerDetailsScreen_parameters.hpp"


namespace SDK
{

// Function WBP_PlayerDetailsScreen.WBP_PlayerDetailsScreen_C.ExecuteUbergraph_WBP_PlayerDetailsScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PlayerDetailsScreen_C::ExecuteUbergraph_WBP_PlayerDetailsScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerDetailsScreen_C", "ExecuteUbergraph_WBP_PlayerDetailsScreen");

	Params::WBP_PlayerDetailsScreen_C_ExecuteUbergraph_WBP_PlayerDetailsScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PlayerDetailsScreen.WBP_PlayerDetailsScreen_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_PlayerDetailsScreen_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerDetailsScreen_C", "PreConstruct");

	Params::WBP_PlayerDetailsScreen_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

