#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsOptionCheckable

#include "Basic.hpp"

#include "WBP_SettingsOptionCheckable_classes.hpp"
#include "WBP_SettingsOptionCheckable_parameters.hpp"


namespace SDK
{

// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.ExecuteUbergraph_WBP_SettingsOptionCheckable
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsOptionCheckable_C::ExecuteUbergraph_WBP_SettingsOptionCheckable(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "ExecuteUbergraph_WBP_SettingsOptionCheckable");

	Params::WBP_SettingsOptionCheckable_C_ExecuteUbergraph_WBP_SettingsOptionCheckable Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_SettingsOptionCheckable_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetFocusLostEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SettingsOptionCheckable_C::BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetFocusLostEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_1_OnWidgetFocusLostEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetFocusReceivedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SettingsOptionCheckable_C::BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetFocusReceivedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetFocusReceivedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.PlayLoop
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsOptionCheckable_C::PlayLoop(float Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "PlayLoop");

	Params::WBP_SettingsOptionCheckable_C_PlayLoop Parms{};

	Parms.Duration = Duration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   UserIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsOptionCheckable_C::BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature(int32 UserIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature");

	Params::WBP_SettingsOptionCheckable_C_BndEvt__InteractiveArea_K2Node_ComponentBoundEvent_0_OnWidgetClickedEvent__DelegateSignature Parms{};

	Parms.UserIndex = UserIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_SettingsOptionCheckable_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.UpdateSelection
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              IsSelected                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SettingsOptionCheckable_C::UpdateSelection(const bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "UpdateSelection");

	Params::WBP_SettingsOptionCheckable_C_UpdateSelection Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsOptionCheckable.WBP_SettingsOptionCheckable_C.SetSelected
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SettingsOptionCheckable_C::SetSelected(bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsOptionCheckable_C", "SetSelected");

	Params::WBP_SettingsOptionCheckable_C_SetSelected Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}

}

