#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatStatusMessage

#include "Basic.hpp"

#include "SDCoreUI_structs.hpp"


namespace SDK::Params
{

// Function WBP_TextChatStatusMessage.WBP_TextChatStatusMessage_C.ExecuteUbergraph_WBP_TextChatStatusMessage
// 0x0008 (0x0008 - 0x0000)
struct WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage) == 0x000004, "Wrong alignment on WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage");
static_assert(sizeof(WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage) == 0x000008, "Wrong size on WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage");
static_assert(offsetof(WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage, EntryPoint) == 0x000000, "Member 'WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_TextChatStatusMessage_C_ExecuteUbergraph_WBP_TextChatStatusMessage::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TextChatStatusMessage.WBP_TextChatStatusMessage_C.Get_AccessibleWidget_AccessibleText_0
// 0x0088 (0x0088 - 0x0000)
struct WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	struct FTextBindable                          NewLocalVar_0;                                     // 0x0018(0x0068)(Edit, BlueprintVisible)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0");
static_assert(sizeof(WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0) == 0x000088, "Wrong size on WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0");
static_assert(offsetof(WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0, NewLocalVar_0) == 0x000018, "Member 'WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0::NewLocalVar_0' has a wrong offset!");
static_assert(offsetof(WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0, CallFunc_IsValid_ReturnValue) == 0x000080, "Member 'WBP_TextChatStatusMessage_C_Get_AccessibleWidget_AccessibleText_0::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

