#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonRewardPreview_Small

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_SeasonRewardPreview_Small.WBP_SeasonRewardPreview_Small_C.ExecuteUbergraph_WBP_SeasonRewardPreview_Small
// 0x0004 (0x0004 - 0x0000)
struct WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small) == 0x000004, "Wrong alignment on WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small");
static_assert(sizeof(WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small) == 0x000004, "Wrong size on WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small");
static_assert(offsetof(WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small, EntryPoint) == 0x000000, "Member 'WBP_SeasonRewardPreview_Small_C_ExecuteUbergraph_WBP_SeasonRewardPreview_Small::EntryPoint' has a wrong offset!");

}

