#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationRoot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CustomizationRoot.WBP_CustomizationRoot_C
// 0x0028 (0x0410 - 0x03E8)
class UWBP_CustomizationRoot_C final : public UMCCCustomizationRootWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       SpinnerEntry;                                      // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       TitleEntry;                                        // 0x03F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           AssetLoaderSpinner;                                // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CustomizationRoot(int32 EntryPoint);
	void PlayStagger();
	void BndEvt__Button_108_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnContextChanged();
	void OnEnterEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CustomizationRoot_C">();
	}
	static class UWBP_CustomizationRoot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomizationRoot_C>();
	}
};
static_assert(alignof(UWBP_CustomizationRoot_C) == 0x000008, "Wrong alignment on UWBP_CustomizationRoot_C");
static_assert(sizeof(UWBP_CustomizationRoot_C) == 0x000410, "Wrong size on UWBP_CustomizationRoot_C");
static_assert(offsetof(UWBP_CustomizationRoot_C, UberGraphFrame) == 0x0003E8, "Member 'UWBP_CustomizationRoot_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationRoot_C, SpinnerEntry) == 0x0003F0, "Member 'UWBP_CustomizationRoot_C::SpinnerEntry' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationRoot_C, TitleEntry) == 0x0003F8, "Member 'UWBP_CustomizationRoot_C::TitleEntry' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationRoot_C, AssetLoaderSpinner) == 0x000400, "Member 'UWBP_CustomizationRoot_C::AssetLoaderSpinner' has a wrong offset!");
static_assert(offsetof(UWBP_CustomizationRoot_C, WBP_ScreenTitle) == 0x000408, "Member 'UWBP_CustomizationRoot_C::WBP_ScreenTitle' has a wrong offset!");

}

