#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonPinnableTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SeasonPinnableTab.WBP_SeasonPinnableTab_C
// 0x0030 (0x05B0 - 0x0580)
class UWBP_SeasonPinnableTab_C final : public UMCCTabWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0580(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 DefaultLine;                                       // 0x0588(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Line;                                              // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SelectedPin;                                       // 0x0598(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Unfeatured;                                        // 0x05A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 UnselectedPin;                                     // 0x05A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_SeasonPinnableTab(int32 EntryPoint);
	void UpdateSelection(const bool IsSelected);
	void UpdateSelectedVisuals(bool bIsSelected);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SeasonPinnableTab_C">();
	}
	static class UWBP_SeasonPinnableTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SeasonPinnableTab_C>();
	}
};
static_assert(alignof(UWBP_SeasonPinnableTab_C) == 0x000008, "Wrong alignment on UWBP_SeasonPinnableTab_C");
static_assert(sizeof(UWBP_SeasonPinnableTab_C) == 0x0005B0, "Wrong size on UWBP_SeasonPinnableTab_C");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, UberGraphFrame) == 0x000580, "Member 'UWBP_SeasonPinnableTab_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, DefaultLine) == 0x000588, "Member 'UWBP_SeasonPinnableTab_C::DefaultLine' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, Line) == 0x000590, "Member 'UWBP_SeasonPinnableTab_C::Line' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, SelectedPin) == 0x000598, "Member 'UWBP_SeasonPinnableTab_C::SelectedPin' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, Unfeatured) == 0x0005A0, "Member 'UWBP_SeasonPinnableTab_C::Unfeatured' has a wrong offset!");
static_assert(offsetof(UWBP_SeasonPinnableTab_C, UnselectedPin) == 0x0005A8, "Member 'UWBP_SeasonPinnableTab_C::UnselectedPin' has a wrong offset!");

}

