#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizationGridWidget

#include "Basic.hpp"

#include "WBP_CustomizationGridWidget_classes.hpp"
#include "WBP_CustomizationGridWidget_parameters.hpp"


namespace SDK
{

// Function WBP_CustomizationGridWidget.WBP_CustomizationGridWidget_C.ExecuteUbergraph_WBP_CustomizationGridWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CustomizationGridWidget_C::ExecuteUbergraph_WBP_CustomizationGridWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationGridWidget_C", "ExecuteUbergraph_WBP_CustomizationGridWidget");

	Params::WBP_CustomizationGridWidget_C_ExecuteUbergraph_WBP_CustomizationGridWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CustomizationGridWidget.WBP_CustomizationGridWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CustomizationGridWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CustomizationGridWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

