#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScrollButtonPrevious

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ScrollButtonPrevious.WBP_ScrollButtonPrevious_C
// 0x0010 (0x0558 - 0x0548)
class UWBP_ScrollButtonPrevious_C final : public UMCCBaseButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0548(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ButtonShadowImage;                                 // 0x0550(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ScrollButtonPrevious(int32 EntryPoint);
	void OnUnhoveredEvent();
	void OnUnfocusedEvent();
	void OnHoveredEvent();
	void OnFocusedEvent();
	void ToggleFocus(ESlateVisibility Visibility_0);
	void ToggleHatching();
	void ToggleArrowColor();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ScrollButtonPrevious_C">();
	}
	static class UWBP_ScrollButtonPrevious_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ScrollButtonPrevious_C>();
	}
};
static_assert(alignof(UWBP_ScrollButtonPrevious_C) == 0x000008, "Wrong alignment on UWBP_ScrollButtonPrevious_C");
static_assert(sizeof(UWBP_ScrollButtonPrevious_C) == 0x000558, "Wrong size on UWBP_ScrollButtonPrevious_C");
static_assert(offsetof(UWBP_ScrollButtonPrevious_C, UberGraphFrame) == 0x000548, "Member 'UWBP_ScrollButtonPrevious_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ScrollButtonPrevious_C, ButtonShadowImage) == 0x000550, "Member 'UWBP_ScrollButtonPrevious_C::ButtonShadowImage' has a wrong offset!");

}

