#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsServerRegions

#include "Basic.hpp"

#include "WBP_SettingsServerRegions_classes.hpp"
#include "WBP_SettingsServerRegions_parameters.hpp"


namespace SDK
{

// Function WBP_SettingsServerRegions.WBP_SettingsServerRegions_C.ExecuteUbergraph_WBP_SettingsServerRegions
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SettingsServerRegions_C::ExecuteUbergraph_WBP_SettingsServerRegions(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsServerRegions_C", "ExecuteUbergraph_WBP_SettingsServerRegions");

	Params::WBP_SettingsServerRegions_C_ExecuteUbergraph_WBP_SettingsServerRegions Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SettingsServerRegions.WBP_SettingsServerRegions_C.OnServersDataChanged
// (Event, Public, BlueprintEvent)

void UWBP_SettingsServerRegions_C::OnServersDataChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsServerRegions_C", "OnServersDataChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingsServerRegions.WBP_SettingsServerRegions_C.PaintRowBackground
// (BlueprintCallable, BlueprintEvent)

void UWBP_SettingsServerRegions_C::PaintRowBackground()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingsServerRegions_C", "PaintRowBackground");

	UObject::ProcessEvent(Func, nullptr);
}

}

