#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsServerRegionRow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SettingsServerRegionRow.WBP_SettingsServerRegionRow_C
// 0x0038 (0x03E0 - 0x03A8)
class UWBP_SettingsServerRegionRow_C final : public UMCCSettingsServerRegionRowWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       GlowAnimation;                                     // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Background;                                        // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Name_0;                                            // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Ping;                                              // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Selection;                                         // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bIsSelected;                                       // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_SettingsServerRegionRow(int32 EntryPoint);
	void UpdateSelection(const bool IsSelected);
	void Construct();
	void OnContextChanged();
	void SetSelected(bool bIsSelected_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SettingsServerRegionRow_C">();
	}
	static class UWBP_SettingsServerRegionRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SettingsServerRegionRow_C>();
	}
};
static_assert(alignof(UWBP_SettingsServerRegionRow_C) == 0x000008, "Wrong alignment on UWBP_SettingsServerRegionRow_C");
static_assert(sizeof(UWBP_SettingsServerRegionRow_C) == 0x0003E0, "Wrong size on UWBP_SettingsServerRegionRow_C");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, UberGraphFrame) == 0x0003A8, "Member 'UWBP_SettingsServerRegionRow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, GlowAnimation) == 0x0003B0, "Member 'UWBP_SettingsServerRegionRow_C::GlowAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, Background) == 0x0003B8, "Member 'UWBP_SettingsServerRegionRow_C::Background' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, Name_0) == 0x0003C0, "Member 'UWBP_SettingsServerRegionRow_C::Name_0' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, Ping) == 0x0003C8, "Member 'UWBP_SettingsServerRegionRow_C::Ping' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, Selection) == 0x0003D0, "Member 'UWBP_SettingsServerRegionRow_C::Selection' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsServerRegionRow_C, bIsSelected) == 0x0003D8, "Member 'UWBP_SettingsServerRegionRow_C::bIsSelected' has a wrong offset!");

}

