#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingsPreviewWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SettingsPreviewWidget.WBP_SettingsPreviewWidget_C
// 0x0098 (0x03E8 - 0x0350)
class UWBP_SettingsPreviewWidget_C final : public UMCCSettingsPreviewWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Controller;                                        // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               CPUTextBlock;                                      // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Description;                                       // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               DescriptionContainer;                              // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               GPUTextBlock;                                      // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableImage*                   Image;                                             // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 KeyboardMouse;                                     // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ColorBlindImagePreview_C*          PreviewColorBlind;                                 // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               PreviewDefault;                                    // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        PreviewSwitcher;                                   // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         ResourceUsageContainer;                            // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               VRamTextBlock;                                     // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GammaImagePreview_C*               WBP_GammaImagePreview;                             // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GammaPreview_C*                    WBP_GammaPreview;                                  // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_SettingsPreviewWidget(int32 EntryPoint);
	void Construct();
	void OnContextChanged();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SettingsPreviewWidget_C">();
	}
	static class UWBP_SettingsPreviewWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SettingsPreviewWidget_C>();
	}
};
static_assert(alignof(UWBP_SettingsPreviewWidget_C) == 0x000008, "Wrong alignment on UWBP_SettingsPreviewWidget_C");
static_assert(sizeof(UWBP_SettingsPreviewWidget_C) == 0x0003E8, "Wrong size on UWBP_SettingsPreviewWidget_C");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, UberGraphFrame) == 0x000350, "Member 'UWBP_SettingsPreviewWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Controller) == 0x000358, "Member 'UWBP_SettingsPreviewWidget_C::Controller' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, CPUTextBlock) == 0x000360, "Member 'UWBP_SettingsPreviewWidget_C::CPUTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Description) == 0x000368, "Member 'UWBP_SettingsPreviewWidget_C::Description' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, DescriptionContainer) == 0x000370, "Member 'UWBP_SettingsPreviewWidget_C::DescriptionContainer' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, GPUTextBlock) == 0x000378, "Member 'UWBP_SettingsPreviewWidget_C::GPUTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Image) == 0x000380, "Member 'UWBP_SettingsPreviewWidget_C::Image' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Image_0) == 0x000388, "Member 'UWBP_SettingsPreviewWidget_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Image_2) == 0x000390, "Member 'UWBP_SettingsPreviewWidget_C::Image_2' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Image_3) == 0x000398, "Member 'UWBP_SettingsPreviewWidget_C::Image_3' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, Image_4) == 0x0003A0, "Member 'UWBP_SettingsPreviewWidget_C::Image_4' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, KeyboardMouse) == 0x0003A8, "Member 'UWBP_SettingsPreviewWidget_C::KeyboardMouse' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, PreviewColorBlind) == 0x0003B0, "Member 'UWBP_SettingsPreviewWidget_C::PreviewColorBlind' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, PreviewDefault) == 0x0003B8, "Member 'UWBP_SettingsPreviewWidget_C::PreviewDefault' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, PreviewSwitcher) == 0x0003C0, "Member 'UWBP_SettingsPreviewWidget_C::PreviewSwitcher' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, ResourceUsageContainer) == 0x0003C8, "Member 'UWBP_SettingsPreviewWidget_C::ResourceUsageContainer' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, VRamTextBlock) == 0x0003D0, "Member 'UWBP_SettingsPreviewWidget_C::VRamTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, WBP_GammaImagePreview) == 0x0003D8, "Member 'UWBP_SettingsPreviewWidget_C::WBP_GammaImagePreview' has a wrong offset!");
static_assert(offsetof(UWBP_SettingsPreviewWidget_C, WBP_GammaPreview) == 0x0003E0, "Member 'UWBP_SettingsPreviewWidget_C::WBP_GammaPreview' has a wrong offset!");

}

