#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMultiplayerCustomGamesBrowseHeaderElement

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "MCC_structs.hpp"


namespace SDK::Params
{

// Function WBP_MCCMultiplayerCustomGamesBrowseHeaderElement.WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C.ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement
// 0x0010 (0x0010 - 0x0000)
struct WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable1;                               // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsSelected;                           // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsHighlighted;                        // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EMCCMultiplayerCustomGamesBrowseScreenSortingOption K2Node_Event_SortingOption;                  // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select1_Default;                            // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement) == 0x000004, "Wrong alignment on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement");
static_assert(sizeof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement) == 0x000010, "Wrong size on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, EntryPoint) == 0x000000, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_bool_Variable) == 0x000004, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_byte_Variable) == 0x000005, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_byte_Variable1) == 0x000006, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_bool_Variable1) == 0x000007, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_byte_Variable2) == 0x000008, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, Temp_byte_Variable3) == 0x000009, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_Event_IsSelected) == 0x00000A, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_Event_IsSelected' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_Select_Default) == 0x00000B, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_Event_IsHighlighted) == 0x00000C, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_Event_IsHighlighted' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_Event_SortingOption) == 0x00000D, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_Event_SortingOption' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_Select1_Default) == 0x00000E, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement, K2Node_SwitchEnum_CmpSuccess) == 0x00000F, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_ExecuteUbergraph_WBP_MCCMultiplayerCustomGamesBrowseHeaderElement::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function WBP_MCCMultiplayerCustomGamesBrowseHeaderElement.WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C.UpdateSortingIcon
// 0x0001 (0x0001 - 0x0000)
struct WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon final
{
public:
	EMCCMultiplayerCustomGamesBrowseScreenSortingOption SortingOption;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon) == 0x000001, "Wrong alignment on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon");
static_assert(sizeof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon) == 0x000001, "Wrong size on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon, SortingOption) == 0x000000, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSortingIcon::SortingOption' has a wrong offset!");

// Function WBP_MCCMultiplayerCustomGamesBrowseHeaderElement.WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C.UpdateHighlighting
// 0x0001 (0x0001 - 0x0000)
struct WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting final
{
public:
	bool                                          IsHighlighted;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting) == 0x000001, "Wrong alignment on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting");
static_assert(sizeof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting) == 0x000001, "Wrong size on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting, IsHighlighted) == 0x000000, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateHighlighting::IsHighlighted' has a wrong offset!");

// Function WBP_MCCMultiplayerCustomGamesBrowseHeaderElement.WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C.UpdateSelection
// 0x0001 (0x0001 - 0x0000)
struct WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection final
{
public:
	bool                                          IsSelected;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection) == 0x000001, "Wrong alignment on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection");
static_assert(sizeof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection) == 0x000001, "Wrong size on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection, IsSelected) == 0x000000, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_UpdateSelection::IsSelected' has a wrong offset!");

// Function WBP_MCCMultiplayerCustomGamesBrowseHeaderElement.WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C.Get_InteractiveArea_AccessibleText_0
// 0x0030 (0x0030 - 0x0000)
struct WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0018(0x0018)()
};
static_assert(alignof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0) == 0x000008, "Wrong alignment on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0");
static_assert(sizeof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0) == 0x000030, "Wrong size on WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0, ReturnValue) == 0x000000, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0, CallFunc_GetText_ReturnValue) == 0x000018, "Member 'WBP_MCCMultiplayerCustomGamesBrowseHeaderElement_C_Get_InteractiveArea_AccessibleText_0::CallFunc_GetText_ReturnValue' has a wrong offset!");

}

