#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InstallerWidget

#include "Basic.hpp"

#include "WBP_InstallerWidget_classes.hpp"
#include "WBP_InstallerWidget_parameters.hpp"


namespace SDK
{

// Function WBP_InstallerWidget.WBP_InstallerWidget_C.ExecuteUbergraph_WBP_InstallerWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InstallerWidget_C::ExecuteUbergraph_WBP_InstallerWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InstallerWidget_C", "ExecuteUbergraph_WBP_InstallerWidget");

	Params::WBP_InstallerWidget_C_ExecuteUbergraph_WBP_InstallerWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InstallerWidget.WBP_InstallerWidget_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_InstallerWidget_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InstallerWidget_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

