#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCMatchmakingHopperDetails

#include "Basic.hpp"

#include "WBP_MCCMatchmakingHopperDetails_classes.hpp"
#include "WBP_MCCMatchmakingHopperDetails_parameters.hpp"


namespace SDK
{

// Function WBP_MCCMatchmakingHopperDetails.WBP_MCCMatchmakingHopperDetails_C.ExecuteUbergraph_WBP_MCCMatchmakingHopperDetails
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MCCMatchmakingHopperDetails_C::ExecuteUbergraph_WBP_MCCMatchmakingHopperDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMatchmakingHopperDetails_C", "ExecuteUbergraph_WBP_MCCMatchmakingHopperDetails");

	Params::WBP_MCCMatchmakingHopperDetails_C_ExecuteUbergraph_WBP_MCCMatchmakingHopperDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MCCMatchmakingHopperDetails.WBP_MCCMatchmakingHopperDetails_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_MCCMatchmakingHopperDetails_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MCCMatchmakingHopperDetails_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

