#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PanelWidgetNavigation

#include "Basic.hpp"

#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PanelWidgetNavigation.WBP_PanelWidgetNavigation_C
// 0x0000 (0x0280 - 0x0280)
class UWBP_PanelWidgetNavigation_C final : public UMCCPanelNavigationWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PanelWidgetNavigation_C">();
	}
	static class UWBP_PanelWidgetNavigation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PanelWidgetNavigation_C>();
	}
};
static_assert(alignof(UWBP_PanelWidgetNavigation_C) == 0x000008, "Wrong alignment on UWBP_PanelWidgetNavigation_C");
static_assert(sizeof(UWBP_PanelWidgetNavigation_C) == 0x000280, "Wrong size on UWBP_PanelWidgetNavigation_C");

}

