#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PGCRLevelUp

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_PGCRLevelUp.WBP_PGCRLevelUp_C.ExecuteUbergraph_WBP_PGCRLevelUp
// 0x0008 (0x0008 - 0x0000)
struct WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp) == 0x000004, "Wrong alignment on WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp");
static_assert(sizeof(WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp) == 0x000008, "Wrong size on WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp");
static_assert(offsetof(WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp, EntryPoint) == 0x000000, "Member 'WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'WBP_PGCRLevelUp_C_ExecuteUbergraph_WBP_PGCRLevelUp::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

