#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StoreUpcomingFlair

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_StoreUpcomingFlair.WBP_StoreUpcomingFlair_C
// 0x0000 (0x0268 - 0x0268)
class UWBP_StoreUpcomingFlair_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_StoreUpcomingFlair_C">();
	}
	static class UWBP_StoreUpcomingFlair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_StoreUpcomingFlair_C>();
	}
};
static_assert(alignof(UWBP_StoreUpcomingFlair_C) == 0x000008, "Wrong alignment on UWBP_StoreUpcomingFlair_C");
static_assert(sizeof(UWBP_StoreUpcomingFlair_C) == 0x000268, "Wrong size on UWBP_StoreUpcomingFlair_C");

}

