#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCUIPopupAuthentication

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MCCUIPopupAuthentication.WBP_MCCUIPopupAuthentication_C
// 0x0028 (0x03C8 - 0x03A0)
class UWBP_MCCUIPopupAuthentication_C final : public UMCCUIPopupAuthentication
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       MoveUp;                                            // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeIn;                                            // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackgroundDarkening;                               // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               Dialog;                                            // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MCCUIPopupAuthentication(int32 EntryPoint);
	void Construct();
	void OnEnterEvent();
	void OnExitEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MCCUIPopupAuthentication_C">();
	}
	static class UWBP_MCCUIPopupAuthentication_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MCCUIPopupAuthentication_C>();
	}
};
static_assert(alignof(UWBP_MCCUIPopupAuthentication_C) == 0x000008, "Wrong alignment on UWBP_MCCUIPopupAuthentication_C");
static_assert(sizeof(UWBP_MCCUIPopupAuthentication_C) == 0x0003C8, "Wrong size on UWBP_MCCUIPopupAuthentication_C");
static_assert(offsetof(UWBP_MCCUIPopupAuthentication_C, UberGraphFrame) == 0x0003A0, "Member 'UWBP_MCCUIPopupAuthentication_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MCCUIPopupAuthentication_C, MoveUp) == 0x0003A8, "Member 'UWBP_MCCUIPopupAuthentication_C::MoveUp' has a wrong offset!");
static_assert(offsetof(UWBP_MCCUIPopupAuthentication_C, FadeIn) == 0x0003B0, "Member 'UWBP_MCCUIPopupAuthentication_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UWBP_MCCUIPopupAuthentication_C, BackgroundDarkening) == 0x0003B8, "Member 'UWBP_MCCUIPopupAuthentication_C::BackgroundDarkening' has a wrong offset!");
static_assert(offsetof(UWBP_MCCUIPopupAuthentication_C, Dialog) == 0x0003C0, "Member 'UWBP_MCCUIPopupAuthentication_C::Dialog' has a wrong offset!");

}

