#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServerPingEntry

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_ServerPingEntry.WBP_ServerPingEntry_C.ExecuteUbergraph_WBP_ServerPingEntry
// 0x0018 (0x0018 - 0x0000)
struct WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMCCPingEntryViewModel*                 K2Node_DynamicCast_AsMCCPing_Entry_View_Model;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry) == 0x000008, "Wrong alignment on WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry");
static_assert(sizeof(WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry) == 0x000018, "Wrong size on WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry");
static_assert(offsetof(WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry, EntryPoint) == 0x000000, "Member 'WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry, K2Node_DynamicCast_AsMCCPing_Entry_View_Model) == 0x000008, "Member 'WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry::K2Node_DynamicCast_AsMCCPing_Entry_View_Model' has a wrong offset!");
static_assert(offsetof(WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'WBP_ServerPingEntry_C_ExecuteUbergraph_WBP_ServerPingEntry::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

