#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerHubPreviewPanel

#include "Basic.hpp"

#include "WBP_PlayerHubPreviewPanel_classes.hpp"
#include "WBP_PlayerHubPreviewPanel_parameters.hpp"


namespace SDK
{

// Function WBP_PlayerHubPreviewPanel.WBP_PlayerHubPreviewPanel_C.GetBackground_0
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWBP_PlayerHubPreviewPanel_C::GetBackground_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PlayerHubPreviewPanel_C", "GetBackground_0");

	Params::WBP_PlayerHubPreviewPanel_C_GetBackground_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

