#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ContextualPreview

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ContextualPreview.WBP_ContextualPreview_C
// 0x0068 (0x03A0 - 0x0338)
class UWBP_ContextualPreview_C final : public UMCCMenuContextualPreviewWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               CompletedCount;                                    // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           ContextPreviewParent;                              // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        ContextSwitcher;                                   // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               DescriptionText;                                   // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           DifficultyImage;                                   // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           GameIcon;                                          // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               GameName;                                          // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               LabelCompletionText;                               // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           ThumbnailImage;                                    // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               Title;                                             // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USDConfigurableTextBlock*               TotalCount;                                        // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ContextualPreview(int32 EntryPoint);
	void OnContextChanged();
	void OptionSelected();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ContextualPreview_C">();
	}
	static class UWBP_ContextualPreview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ContextualPreview_C>();
	}
};
static_assert(alignof(UWBP_ContextualPreview_C) == 0x000008, "Wrong alignment on UWBP_ContextualPreview_C");
static_assert(sizeof(UWBP_ContextualPreview_C) == 0x0003A0, "Wrong size on UWBP_ContextualPreview_C");
static_assert(offsetof(UWBP_ContextualPreview_C, UberGraphFrame) == 0x000338, "Member 'UWBP_ContextualPreview_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, FadeIn) == 0x000340, "Member 'UWBP_ContextualPreview_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, CompletedCount) == 0x000348, "Member 'UWBP_ContextualPreview_C::CompletedCount' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, ContextPreviewParent) == 0x000350, "Member 'UWBP_ContextualPreview_C::ContextPreviewParent' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, ContextSwitcher) == 0x000358, "Member 'UWBP_ContextualPreview_C::ContextSwitcher' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, DescriptionText) == 0x000360, "Member 'UWBP_ContextualPreview_C::DescriptionText' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, DifficultyImage) == 0x000368, "Member 'UWBP_ContextualPreview_C::DifficultyImage' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, GameIcon) == 0x000370, "Member 'UWBP_ContextualPreview_C::GameIcon' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, GameName) == 0x000378, "Member 'UWBP_ContextualPreview_C::GameName' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, LabelCompletionText) == 0x000380, "Member 'UWBP_ContextualPreview_C::LabelCompletionText' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, ThumbnailImage) == 0x000388, "Member 'UWBP_ContextualPreview_C::ThumbnailImage' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, Title) == 0x000390, "Member 'UWBP_ContextualPreview_C::Title' has a wrong offset!");
static_assert(offsetof(UWBP_ContextualPreview_C, TotalCount) == 0x000398, "Member 'UWBP_ContextualPreview_C::TotalCount' has a wrong offset!");

}

