#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StoreBundleScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MCC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_StoreBundleScreen.WBP_StoreBundleScreen_C
// 0x0048 (0x04B0 - 0x0468)
class UWBP_StoreBundleScreen_C final : public UMCCStoreBundleScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0468(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       PurchaseFlyIn;                                     // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       SpinnerEntry;                                      // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       TitleEntry;                                        // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMCCUUIImage*                           AssetLoaderSpinner;                                // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Check;                                             // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     WBP_ScreenTitle;                                   // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_StoreBundleScreen(int32 EntryPoint);
	void OnBundleUnlocked();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnContextChanged();
	void OnEnterEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_StoreBundleScreen_C">();
	}
	static class UWBP_StoreBundleScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_StoreBundleScreen_C>();
	}
};
static_assert(alignof(UWBP_StoreBundleScreen_C) == 0x000008, "Wrong alignment on UWBP_StoreBundleScreen_C");
static_assert(sizeof(UWBP_StoreBundleScreen_C) == 0x0004B0, "Wrong size on UWBP_StoreBundleScreen_C");
static_assert(offsetof(UWBP_StoreBundleScreen_C, UberGraphFrame) == 0x000468, "Member 'UWBP_StoreBundleScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, PurchaseFlyIn) == 0x000470, "Member 'UWBP_StoreBundleScreen_C::PurchaseFlyIn' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, SpinnerEntry) == 0x000478, "Member 'UWBP_StoreBundleScreen_C::SpinnerEntry' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, TitleEntry) == 0x000480, "Member 'UWBP_StoreBundleScreen_C::TitleEntry' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, AssetLoaderSpinner) == 0x000488, "Member 'UWBP_StoreBundleScreen_C::AssetLoaderSpinner' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, Check) == 0x000490, "Member 'UWBP_StoreBundleScreen_C::Check' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, Image_0) == 0x000498, "Member 'UWBP_StoreBundleScreen_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, Image_1) == 0x0004A0, "Member 'UWBP_StoreBundleScreen_C::Image_1' has a wrong offset!");
static_assert(offsetof(UWBP_StoreBundleScreen_C, WBP_ScreenTitle) == 0x0004A8, "Member 'UWBP_StoreBundleScreen_C::WBP_ScreenTitle' has a wrong offset!");

}

