#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChallengeToast

#include "Basic.hpp"

#include "WBP_ChallengeToast_classes.hpp"
#include "WBP_ChallengeToast_parameters.hpp"


namespace SDK
{

// Function WBP_ChallengeToast.WBP_ChallengeToast_C.ExecuteUbergraph_WBP_ChallengeToast
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChallengeToast_C::ExecuteUbergraph_WBP_ChallengeToast(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChallengeToast_C", "ExecuteUbergraph_WBP_ChallengeToast");

	Params::WBP_ChallengeToast_C_ExecuteUbergraph_WBP_ChallengeToast Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChallengeToast.WBP_ChallengeToast_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_ChallengeToast_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChallengeToast_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

