#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ContextualPreviewStore

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_ContextualPreviewStore.WBP_ContextualPreviewStore_C.ExecuteUbergraph_WBP_ContextualPreviewStore
// 0x0014 (0x0014 - 0x0000)
struct WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent1;                        // 0x0004(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x000C(0x0008)(NoDestructor)
};
static_assert(alignof(WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore) == 0x000004, "Wrong alignment on WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore");
static_assert(sizeof(WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore) == 0x000014, "Wrong size on WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore");
static_assert(offsetof(WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore, EntryPoint) == 0x000000, "Member 'WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore, K2Node_Event_InFocusEvent1) == 0x000004, "Member 'WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore::K2Node_Event_InFocusEvent1' has a wrong offset!");
static_assert(offsetof(WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore, K2Node_Event_InFocusEvent) == 0x00000C, "Member 'WBP_ContextualPreviewStore_C_ExecuteUbergraph_WBP_ContextualPreviewStore::K2Node_Event_InFocusEvent' has a wrong offset!");

// Function WBP_ContextualPreviewStore.WBP_ContextualPreviewStore_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_ContextualPreviewStore_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_ContextualPreviewStore_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on WBP_ContextualPreviewStore_C_OnAddedToFocusPath");
static_assert(sizeof(WBP_ContextualPreviewStore_C_OnAddedToFocusPath) == 0x000008, "Wrong size on WBP_ContextualPreviewStore_C_OnAddedToFocusPath");
static_assert(offsetof(WBP_ContextualPreviewStore_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_ContextualPreviewStore_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_ContextualPreviewStore.WBP_ContextualPreviewStore_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath");
static_assert(sizeof(WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath");
static_assert(offsetof(WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_ContextualPreviewStore_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

}

