#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MCCInstallProgress

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_MCCInstallProgress.WBP_MCCInstallProgress_C.ExecuteUbergraph_WBP_MCCInstallProgress
// 0x0020 (0x0020 - 0x0000)
struct WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress) == 0x000008, "Wrong alignment on WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress");
static_assert(sizeof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress) == 0x000020, "Wrong size on WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress");
static_assert(offsetof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress, EntryPoint) == 0x000000, "Member 'WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress, CallFunc_MakeLiteralName_ReturnValue) == 0x000008, "Member 'WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress::CallFunc_MakeLiteralName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000018, "Member 'WBP_MCCInstallProgress_C_ExecuteUbergraph_WBP_MCCInstallProgress::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");

}

